BEGIN;
INSERT INTO exams (id,title,description,year_level,domain,time_limit_seconds,available_from,available_until,status,created_by,package_type,scoring_config) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','Year 7 Grammar & Punctuation — Premium Practice Exam 10','Original NAPLAN-style Year 7 Grammar & Punctuation digital practice exam.',7,'GRAMMAR_PUNCTUATION',2700,NULL,NULL,'PUBLISHED',NULL,'PREMIUM',NULL);
INSERT INTO exam_sections (id,exam_id,title,section_order,time_limit_seconds,calculator_allowed,navigation_locked,domain,instructions) VALUES ('8ec52684-c516-5a9f-8097-0035b2c9ea2b','dba6fd96-8986-5337-a339-43901829c0de','Grammar & Punctuation adaptive digital section',1,2700,FALSE,FALSE,'GRAMMAR_PUNCTUATION','Complete the adaptive practice section; the next testlet is selected by the configured routing rules.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('340caa92-2f67-5783-a18e-659dadd73760','8ec52684-c516-5a9f-8097-0035b2c9ea2b',NULL,'A — Grammar & Punctuation adaptive node',1,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('1c2c236f-2f61-5f9b-8265-4e98b2e218b2','8ec52684-c516-5a9f-8097-0035b2c9ea2b',NULL,'B — Grammar & Punctuation adaptive node',2,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('e70f67b3-de4d-5d54-9ce3-84be9bd8f81e','8ec52684-c516-5a9f-8097-0035b2c9ea2b',NULL,'B_LATE — Grammar & Punctuation adaptive node',3,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('763638cc-564e-5ac2-9d5a-3c39efd2d14e','8ec52684-c516-5a9f-8097-0035b2c9ea2b',NULL,'C — Grammar & Punctuation adaptive node',4,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('1a1deb0f-0fda-5c43-a420-c8dbe2b43a97','8ec52684-c516-5a9f-8097-0035b2c9ea2b',NULL,'C_EARLY — Grammar & Punctuation adaptive node',5,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('92489daa-f195-5c4d-b80b-919f9bce8710','8ec52684-c516-5a9f-8097-0035b2c9ea2b',NULL,'D — Grammar & Punctuation adaptive node',6,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('1f0169b5-b398-5c57-9bab-1c4038ee8893','8ec52684-c516-5a9f-8097-0035b2c9ea2b',NULL,'E — Grammar & Punctuation adaptive node',7,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('065d9662-a911-55c9-b333-c1ff7eccfa06','8ec52684-c516-5a9f-8097-0035b2c9ea2b',NULL,'F — Grammar & Punctuation adaptive node',8,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('bae5dc5c-92f7-5eda-b297-5b8cb234d9ed', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 4, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','bae5dc5c-92f7-5eda-b297-5b8cb234d9ed',1,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','340caa92-2f67-5783-a18e-659dadd73760') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('966241d5-bfa1-5f1a-8d3c-03cf862df29a', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 5, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','966241d5-bfa1-5f1a-8d3c-03cf862df29a',2,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','340caa92-2f67-5783-a18e-659dadd73760') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('f7d135f3-382a-54fe-af69-2f3ee4765dc2', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 4, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','f7d135f3-382a-54fe-af69-2f3ee4765dc2',3,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','340caa92-2f67-5783-a18e-659dadd73760') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('379bda6c-d927-52d8-8776-3f294519df1a', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 5, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','379bda6c-d927-52d8-8776-3f294519df1a',4,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','340caa92-2f67-5783-a18e-659dadd73760') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b4bef8d0-db91-5d33-9639-e7490c03169a', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 4, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','b4bef8d0-db91-5d33-9639-e7490c03169a',5,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','340caa92-2f67-5783-a18e-659dadd73760') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('971ef59d-a868-558f-9d8a-b74009213737', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 5, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','971ef59d-a868-558f-9d8a-b74009213737',6,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','340caa92-2f67-5783-a18e-659dadd73760') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('71d4347c-0aa3-5fdb-abc9-0a1f86e5170f', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','71d4347c-0aa3-5fdb-abc9-0a1f86e5170f',7,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','340caa92-2f67-5783-a18e-659dadd73760') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('ec3bf38a-c95a-5c85-86cb-c07993b8dc21', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','ec3bf38a-c95a-5c85-86cb-c07993b8dc21',8,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','340caa92-2f67-5783-a18e-659dadd73760') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('74a8eaff-d506-5d72-b3c1-6b08a0776301', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things, whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','74a8eaff-d506-5d72-b3c1-6b08a0776301',9,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','340caa92-2f67-5783-a18e-659dadd73760') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('bd8340fd-7f71-513d-96ae-a61da292b8c0', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 4, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','bd8340fd-7f71-513d-96ae-a61da292b8c0',10,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1c2c236f-2f61-5f9b-8265-4e98b2e218b2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('18d060fb-798a-58b3-bef3-ada254320a0f', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 5, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','18d060fb-798a-58b3-bef3-ada254320a0f',11,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1c2c236f-2f61-5f9b-8265-4e98b2e218b2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('8c5c5fc2-3dce-5510-906a-b0673c8c29df', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 4, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','8c5c5fc2-3dce-5510-906a-b0673c8c29df',12,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1c2c236f-2f61-5f9b-8265-4e98b2e218b2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('52e93dd3-5658-52db-bcc9-307e863d6391', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 5, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','52e93dd3-5658-52db-bcc9-307e863d6391',13,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1c2c236f-2f61-5f9b-8265-4e98b2e218b2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('08402cb3-0f8c-54b9-83bb-1c54e38c20a6', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 4, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','08402cb3-0f8c-54b9-83bb-1c54e38c20a6',14,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1c2c236f-2f61-5f9b-8265-4e98b2e218b2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('4b53b271-33d5-525b-abde-c9b367d4d663', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 5, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','4b53b271-33d5-525b-abde-c9b367d4d663',15,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1c2c236f-2f61-5f9b-8265-4e98b2e218b2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('1edaf8f1-5a8a-5e5f-b08b-d14984f87ef5', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','1edaf8f1-5a8a-5e5f-b08b-d14984f87ef5',16,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1c2c236f-2f61-5f9b-8265-4e98b2e218b2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('87c32903-9e8b-5c4d-b793-8fb7443e0d76', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things, whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','87c32903-9e8b-5c4d-b793-8fb7443e0d76',17,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1c2c236f-2f61-5f9b-8265-4e98b2e218b2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('bb8335cb-c95b-5f6e-bed4-c7bc3cbac5e5', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, ‘I will finish the poster tomorrow.’"},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','bb8335cb-c95b-5f6e-bed4-c7bc3cbac5e5',18,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1c2c236f-2f61-5f9b-8265-4e98b2e218b2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('64d26515-84b0-55fd-ae2c-b5cac2c42373', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 5, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','64d26515-84b0-55fd-ae2c-b5cac2c42373',19,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','e70f67b3-de4d-5d54-9ce3-84be9bd8f81e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('c3eeaaa6-c720-5d0f-89cd-eb7e1bd51f09', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 6, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','c3eeaaa6-c720-5d0f-89cd-eb7e1bd51f09',20,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','e70f67b3-de4d-5d54-9ce3-84be9bd8f81e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('209f484b-4b9d-5b0c-9f66-b4a81c4da9ab', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 5, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','209f484b-4b9d-5b0c-9f66-b4a81c4da9ab',21,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','e70f67b3-de4d-5d54-9ce3-84be9bd8f81e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d47c768d-3347-5aab-aaae-1326e8125902', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 6, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','d47c768d-3347-5aab-aaae-1326e8125902',22,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','e70f67b3-de4d-5d54-9ce3-84be9bd8f81e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('a084d8aa-c10a-50d1-906e-26eb0d20c768', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 5, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','a084d8aa-c10a-50d1-906e-26eb0d20c768',23,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','e70f67b3-de4d-5d54-9ce3-84be9bd8f81e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('57ed743f-9ab1-55c0-a6e6-696d3b84894e', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 6, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','57ed743f-9ab1-55c0-a6e6-696d3b84894e',24,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','e70f67b3-de4d-5d54-9ce3-84be9bd8f81e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('3e1c29f3-c75d-56c9-b782-f0893e2bf159', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things, whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','3e1c29f3-c75d-56c9-b782-f0893e2bf159',25,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','e70f67b3-de4d-5d54-9ce3-84be9bd8f81e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b2dd9b66-1def-515c-8b95-47a08f84cd84', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, ‘I will finish the poster tomorrow.’"},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','b2dd9b66-1def-515c-8b95-47a08f84cd84',26,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','e70f67b3-de4d-5d54-9ce3-84be9bd8f81e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('40f5a6ab-1502-5af9-a841-66caddc54be8', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','40f5a6ab-1502-5af9-a841-66caddc54be8',27,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','e70f67b3-de4d-5d54-9ce3-84be9bd8f81e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('e51ad2ad-b7d5-5487-8526-9fcce7d00fc7', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 5, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','e51ad2ad-b7d5-5487-8526-9fcce7d00fc7',28,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','763638cc-564e-5ac2-9d5a-3c39efd2d14e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('fbf5c2eb-0ba1-5323-b090-37c62cc5d8eb', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 6, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','fbf5c2eb-0ba1-5323-b090-37c62cc5d8eb',29,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','763638cc-564e-5ac2-9d5a-3c39efd2d14e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('c4a3b22e-9500-5d4c-b5a5-2f51c7c19b09', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 5, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','c4a3b22e-9500-5d4c-b5a5-2f51c7c19b09',30,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','763638cc-564e-5ac2-9d5a-3c39efd2d14e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('28d5c742-2d9d-53a1-aace-b3b090028b4b', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 6, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','28d5c742-2d9d-53a1-aace-b3b090028b4b',31,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','763638cc-564e-5ac2-9d5a-3c39efd2d14e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('a0e7eaf8-517c-5048-84ec-c0c144c86098', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 5, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','a0e7eaf8-517c-5048-84ec-c0c144c86098',32,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','763638cc-564e-5ac2-9d5a-3c39efd2d14e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('34b5ef08-deab-50b1-a168-571dcdbf7c88', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 6, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','34b5ef08-deab-50b1-a168-571dcdbf7c88',33,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','763638cc-564e-5ac2-9d5a-3c39efd2d14e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('12bc028e-5d4c-5957-9c6e-bfd43df66897', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, ‘I will finish the poster tomorrow.’"},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','12bc028e-5d4c-5957-9c6e-bfd43df66897',34,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','763638cc-564e-5ac2-9d5a-3c39efd2d14e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('faffbe48-0748-52ee-8a0b-ee15256faa35', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','faffbe48-0748-52ee-8a0b-ee15256faa35',35,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','763638cc-564e-5ac2-9d5a-3c39efd2d14e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d5da2646-f839-5ea2-afa6-7bc4dabd907e', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','d5da2646-f839-5ea2-afa6-7bc4dabd907e',36,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','763638cc-564e-5ac2-9d5a-3c39efd2d14e') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('0dd39329-c011-5137-88df-c73739f72794', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 6, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','0dd39329-c011-5137-88df-c73739f72794',37,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1a1deb0f-0fda-5c43-a420-c8dbe2b43a97') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('6f8b9e20-4935-5edb-bc63-0da456368a4e', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 7, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','6f8b9e20-4935-5edb-bc63-0da456368a4e',38,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1a1deb0f-0fda-5c43-a420-c8dbe2b43a97') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d36d251d-51bf-5d0c-9001-be48d4aa9b67', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 6, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','d36d251d-51bf-5d0c-9001-be48d4aa9b67',39,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1a1deb0f-0fda-5c43-a420-c8dbe2b43a97') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('288a5f39-a0ed-5be1-b110-2c3308cdc1fc', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 7, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','288a5f39-a0ed-5be1-b110-2c3308cdc1fc',40,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1a1deb0f-0fda-5c43-a420-c8dbe2b43a97') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('cf57b5c6-648d-5697-8b97-da20a69ed7e4', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 6, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','cf57b5c6-648d-5697-8b97-da20a69ed7e4',41,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1a1deb0f-0fda-5c43-a420-c8dbe2b43a97') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('84b3346b-4955-5c06-8ea9-680e9860ef93', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 7, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','84b3346b-4955-5c06-8ea9-680e9860ef93',42,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1a1deb0f-0fda-5c43-a420-c8dbe2b43a97') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9660a035-964c-53b9-b72f-c314953a3630', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','9660a035-964c-53b9-b72f-c314953a3630',43,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1a1deb0f-0fda-5c43-a420-c8dbe2b43a97') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('1a03989d-79c1-5e1d-98ea-099f366c55fd', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','1a03989d-79c1-5e1d-98ea-099f366c55fd',44,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1a1deb0f-0fda-5c43-a420-c8dbe2b43a97') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('190ea5cf-5c87-5e73-a0fb-2d638e8049fa', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things, whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','190ea5cf-5c87-5e73-a0fb-2d638e8049fa',45,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1a1deb0f-0fda-5c43-a420-c8dbe2b43a97') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('1bd4b114-6bab-58e0-ba2f-7891566ae731', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 6, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','1bd4b114-6bab-58e0-ba2f-7891566ae731',46,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','92489daa-f195-5c4d-b80b-919f9bce8710') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('1467b0f2-93b2-5d3a-ad39-d95eca1f1094', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 7, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','1467b0f2-93b2-5d3a-ad39-d95eca1f1094',47,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','92489daa-f195-5c4d-b80b-919f9bce8710') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('be7f9526-7050-525d-8250-e4723eecb057', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 6, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','be7f9526-7050-525d-8250-e4723eecb057',48,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','92489daa-f195-5c4d-b80b-919f9bce8710') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('28d0f878-b666-59d4-9010-34e6b847322d', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 7, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','28d0f878-b666-59d4-9010-34e6b847322d',49,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','92489daa-f195-5c4d-b80b-919f9bce8710') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b4fdc9e1-9137-5d86-997c-3cc2ec15fca9', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 6, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','b4fdc9e1-9137-5d86-997c-3cc2ec15fca9',50,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','92489daa-f195-5c4d-b80b-919f9bce8710') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9d5f4d7c-8eca-5d60-aacf-0b1fe619f290', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 7, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','9d5f4d7c-8eca-5d60-aacf-0b1fe619f290',51,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','92489daa-f195-5c4d-b80b-919f9bce8710') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('4046e09f-7d78-52d0-910b-c7a7ca8a832a', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','4046e09f-7d78-52d0-910b-c7a7ca8a832a',52,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','92489daa-f195-5c4d-b80b-919f9bce8710') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('88750265-df7a-5d89-ad63-1479a370e66d', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things, whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','88750265-df7a-5d89-ad63-1479a370e66d',53,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','92489daa-f195-5c4d-b80b-919f9bce8710') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('e37ab0ba-7c0e-5939-b3e5-f06471dcfa60', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, ‘I will finish the poster tomorrow.’"},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','e37ab0ba-7c0e-5939-b3e5-f06471dcfa60',54,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','92489daa-f195-5c4d-b80b-919f9bce8710') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('deb2ac16-eba2-5809-8a5a-02244d4e07d4', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 7, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','deb2ac16-eba2-5809-8a5a-02244d4e07d4',55,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1f0169b5-b398-5c57-9bab-1c4038ee8893') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('40ce0dac-75ba-5495-a679-259877f990e7', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 8, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','40ce0dac-75ba-5495-a679-259877f990e7',56,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1f0169b5-b398-5c57-9bab-1c4038ee8893') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('bc1c2960-ba1d-5a66-a56d-14d21b29e749', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 7, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','bc1c2960-ba1d-5a66-a56d-14d21b29e749',57,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1f0169b5-b398-5c57-9bab-1c4038ee8893') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('98d0d7b5-e642-54e2-a134-42be670f8f17', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 8, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','98d0d7b5-e642-54e2-a134-42be670f8f17',58,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1f0169b5-b398-5c57-9bab-1c4038ee8893') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('32008e74-4021-5bee-9304-7714fd0b95c0', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 7, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','32008e74-4021-5bee-9304-7714fd0b95c0',59,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1f0169b5-b398-5c57-9bab-1c4038ee8893') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('15f463e7-af00-59c6-9e8f-1c10ea0167de', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 8, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','15f463e7-af00-59c6-9e8f-1c10ea0167de',60,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1f0169b5-b398-5c57-9bab-1c4038ee8893') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('eae1a10b-1b44-57d5-a122-11ecde982fe1', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things, whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','eae1a10b-1b44-57d5-a122-11ecde982fe1',61,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1f0169b5-b398-5c57-9bab-1c4038ee8893') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('2746dec7-7faa-5074-bbeb-ff7e368d9094', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 8, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, ‘I will finish the poster tomorrow.’"},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','2746dec7-7faa-5074-bbeb-ff7e368d9094',62,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1f0169b5-b398-5c57-9bab-1c4038ee8893') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('50d549bf-d26b-5eab-97f1-27710e736e6d', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','50d549bf-d26b-5eab-97f1-27710e736e6d',63,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','1f0169b5-b398-5c57-9bab-1c4038ee8893') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('26cfd66e-c0df-5d10-89dc-fb799a35a296', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 7, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','26cfd66e-c0df-5d10-89dc-fb799a35a296',64,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','065d9662-a911-55c9-b333-c1ff7eccfa06') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('20078f65-f50c-5660-8962-24a858cd671d', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 8, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','20078f65-f50c-5660-8962-24a858cd671d',65,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','065d9662-a911-55c9-b333-c1ff7eccfa06') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('861d17ea-c4b1-53f9-8068-72c136449796', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 7, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','861d17ea-c4b1-53f9-8068-72c136449796',66,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','065d9662-a911-55c9-b333-c1ff7eccfa06') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('f6719ae5-3542-5c7b-a165-400bb3c50739', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 8, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','f6719ae5-3542-5c7b-a165-400bb3c50739',67,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','065d9662-a911-55c9-b333-c1ff7eccfa06') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('ed8cfa91-f092-5ce3-b571-ea59f8d653a9', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 7, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','ed8cfa91-f092-5ce3-b571-ea59f8d653a9',68,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','065d9662-a911-55c9-b333-c1ff7eccfa06') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('2cb33697-d047-5c94-b182-33d216f9d5ae', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 8, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','2cb33697-d047-5c94-b182-33d216f9d5ae',69,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','065d9662-a911-55c9-b333-c1ff7eccfa06') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d775a13a-8b0e-576f-b3b2-f36b135e65ae', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, ‘I will finish the poster tomorrow.’"},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','d775a13a-8b0e-576f-b3b2-f36b135e65ae',70,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','065d9662-a911-55c9-b333-c1ff7eccfa06') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9a1e8b3d-1f74-562e-80b3-0972fc23c8a0', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 8, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','9a1e8b3d-1f74-562e-80b3-0972fc23c8a0',71,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','065d9662-a911-55c9-b333-c1ff7eccfa06') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('c98e0c8a-4d49-5393-9596-e2348705349b', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('dba6fd96-8986-5337-a339-43901829c0de','c98e0c8a-4d49-5393-9596-e2348705349b',72,'8ec52684-c516-5a9f-8097-0035b2c9ea2b','065d9662-a911-55c9-b333-c1ff7eccfa06') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('d5240886-7864-5780-a223-0a650bd1ff94','dba6fd96-8986-5337-a339-43901829c0de','340caa92-2f67-5783-a18e-659dadd73760','1a1deb0f-0fda-5c43-a420-c8dbe2b43a97','SCORE_BELOW','{"threshold":0.35}'::jsonb,30);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('3a653672-6bbd-5660-9a77-f444a24bb399','dba6fd96-8986-5337-a339-43901829c0de','340caa92-2f67-5783-a18e-659dadd73760','92489daa-f195-5c4d-b80b-919f9bce8710','SCORE_ABOVE','{"threshold":0.65}'::jsonb,20);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('beff5371-1770-5c65-9b82-7fdb56c86d1a','dba6fd96-8986-5337-a339-43901829c0de','340caa92-2f67-5783-a18e-659dadd73760','1c2c236f-2f61-5f9b-8265-4e98b2e218b2','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('0a796c6f-5310-56b4-b247-100485086760','dba6fd96-8986-5337-a339-43901829c0de','1c2c236f-2f61-5f9b-8265-4e98b2e218b2','1f0169b5-b398-5c57-9bab-1c4038ee8893','SCORE_ABOVE','{"threshold":0.7}'::jsonb,10);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('990413f4-28b1-55f3-9ec5-cd4c6ea2e0a4','dba6fd96-8986-5337-a339-43901829c0de','1c2c236f-2f61-5f9b-8265-4e98b2e218b2','763638cc-564e-5ac2-9d5a-3c39efd2d14e','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('c71d78d7-51f4-5d7f-8377-b4786cf17564','dba6fd96-8986-5337-a339-43901829c0de','92489daa-f195-5c4d-b80b-919f9bce8710','065d9662-a911-55c9-b333-c1ff7eccfa06','SCORE_ABOVE','{"threshold":0.7}'::jsonb,10);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('f4366322-2b21-5d7a-b703-21b0b004fb06','dba6fd96-8986-5337-a339-43901829c0de','92489daa-f195-5c4d-b80b-919f9bce8710','763638cc-564e-5ac2-9d5a-3c39efd2d14e','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('20d7a067-0072-55f0-9f02-eaea02862bb1','dba6fd96-8986-5337-a339-43901829c0de','1a1deb0f-0fda-5c43-a420-c8dbe2b43a97','e70f67b3-de4d-5d54-9ce3-84be9bd8f81e','ALWAYS',NULL,0);
COMMIT;
