BEGIN;
INSERT INTO exams (id,title,description,year_level,domain,time_limit_seconds,available_from,available_until,status,created_by,package_type,scoring_config) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','Year 9 Grammar & Punctuation — Premium Practice Exam 03','Original NAPLAN-style Year 9 Grammar & Punctuation digital practice exam.',9,'GRAMMAR_PUNCTUATION',2700,NULL,NULL,'PUBLISHED',NULL,'PREMIUM',NULL);
INSERT INTO exam_sections (id,exam_id,title,section_order,time_limit_seconds,calculator_allowed,navigation_locked,domain,instructions) VALUES ('a471dfe4-961a-5c7f-a4de-7337e4b5b620','5948272f-52c8-54ec-8112-66e9734c5bcf','Grammar & Punctuation adaptive digital section',1,2700,FALSE,FALSE,'GRAMMAR_PUNCTUATION','Complete the adaptive practice section; the next testlet is selected by the configured routing rules.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('d83bd2b6-2ae6-5e20-a516-ba26397bd1a5','a471dfe4-961a-5c7f-a4de-7337e4b5b620',NULL,'A — Grammar & Punctuation adaptive node',1,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('c53294a1-a810-56c6-852e-67480eeeb2e4','a471dfe4-961a-5c7f-a4de-7337e4b5b620',NULL,'B — Grammar & Punctuation adaptive node',2,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('8a4727e6-fbe6-5432-b4a8-599602335537','a471dfe4-961a-5c7f-a4de-7337e4b5b620',NULL,'B_LATE — Grammar & Punctuation adaptive node',3,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('421cace9-7377-5321-b974-fc7778de50a2','a471dfe4-961a-5c7f-a4de-7337e4b5b620',NULL,'C — Grammar & Punctuation adaptive node',4,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('6067749b-1a6c-55fd-bdc1-5770c9b50336','a471dfe4-961a-5c7f-a4de-7337e4b5b620',NULL,'C_EARLY — Grammar & Punctuation adaptive node',5,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('d2466b20-d76d-5af2-a84d-61797bb807e1','a471dfe4-961a-5c7f-a4de-7337e4b5b620',NULL,'D — Grammar & Punctuation adaptive node',6,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('7a5ce1e2-e9d1-5766-90d6-f1bf75082918','a471dfe4-961a-5c7f-a4de-7337e4b5b620',NULL,'E — Grammar & Punctuation adaptive node',7,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('9eb0124e-c2f2-5f44-b423-bd8127515c1f','a471dfe4-961a-5c7f-a4de-7337e4b5b620',NULL,'F — Grammar & Punctuation adaptive node',8,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('93765584-2d72-58ce-a4d6-bbb432398bfc', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 4, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','93765584-2d72-58ce-a4d6-bbb432398bfc',1,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d83bd2b6-2ae6-5e20-a516-ba26397bd1a5') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('7252e1c7-ada1-5111-991c-465c0eeb43cf', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 5, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','7252e1c7-ada1-5111-991c-465c0eeb43cf',2,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d83bd2b6-2ae6-5e20-a516-ba26397bd1a5') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('56fed058-c8bb-53ca-8261-26b2b6556806', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 4, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','56fed058-c8bb-53ca-8261-26b2b6556806',3,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d83bd2b6-2ae6-5e20-a516-ba26397bd1a5') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('791281a5-e878-58c2-8e7f-7ec1f3897601', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 5, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','791281a5-e878-58c2-8e7f-7ec1f3897601',4,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d83bd2b6-2ae6-5e20-a516-ba26397bd1a5') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('8a55622a-14d2-54cb-973a-d306870461e3', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 4, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','8a55622a-14d2-54cb-973a-d306870461e3',5,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d83bd2b6-2ae6-5e20-a516-ba26397bd1a5') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('63f44b33-75b0-5403-bb01-f27003629476', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 5, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','63f44b33-75b0-5403-bb01-f27003629476',6,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d83bd2b6-2ae6-5e20-a516-ba26397bd1a5') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('fecc5361-af85-5d5b-893b-3cca528aaff2', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','fecc5361-af85-5d5b-893b-3cca528aaff2',7,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d83bd2b6-2ae6-5e20-a516-ba26397bd1a5') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('67bfde8c-e8f7-5f5b-a558-4d6e685574e2', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','67bfde8c-e8f7-5f5b-a558-4d6e685574e2',8,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d83bd2b6-2ae6-5e20-a516-ba26397bd1a5') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('c5eb5051-7f99-5848-a1d7-dcd6c9bd5b75', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','c5eb5051-7f99-5848-a1d7-dcd6c9bd5b75',9,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d83bd2b6-2ae6-5e20-a516-ba26397bd1a5') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('1ef4d430-951e-5d61-943e-99a02d9f1ced', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 4, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','1ef4d430-951e-5d61-943e-99a02d9f1ced',10,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','c53294a1-a810-56c6-852e-67480eeeb2e4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('702d702b-257b-5806-a5cd-5eee18cac130', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 5, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','702d702b-257b-5806-a5cd-5eee18cac130',11,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','c53294a1-a810-56c6-852e-67480eeeb2e4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('7f6d0f03-2c54-557a-83cf-3f5588c860fc', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 4, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','7f6d0f03-2c54-557a-83cf-3f5588c860fc',12,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','c53294a1-a810-56c6-852e-67480eeeb2e4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b46e57bb-a38c-5bde-a956-b7f18865b4e2', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 5, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','b46e57bb-a38c-5bde-a956-b7f18865b4e2',13,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','c53294a1-a810-56c6-852e-67480eeeb2e4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('14033bb1-7bb7-5ff7-b116-aed9c9913f8b', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 4, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','14033bb1-7bb7-5ff7-b116-aed9c9913f8b',14,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','c53294a1-a810-56c6-852e-67480eeeb2e4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('301922c6-80cc-59c3-affb-408fc19b16fc', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 5, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','301922c6-80cc-59c3-affb-408fc19b16fc',15,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','c53294a1-a810-56c6-852e-67480eeeb2e4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b3ade360-32cf-572f-8a9d-cf6a53a033c5', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','b3ade360-32cf-572f-8a9d-cf6a53a033c5',16,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','c53294a1-a810-56c6-852e-67480eeeb2e4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('3325a8b5-f8ff-51c9-bcbf-3f15e000a02c', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','3325a8b5-f8ff-51c9-bcbf-3f15e000a02c',17,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','c53294a1-a810-56c6-852e-67480eeeb2e4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('de07f30d-41f7-529b-95f4-8ce21da6a1cd', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','de07f30d-41f7-529b-95f4-8ce21da6a1cd',18,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','c53294a1-a810-56c6-852e-67480eeeb2e4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('57d2f1e7-0547-556b-859a-49d939152f24', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 5, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','57d2f1e7-0547-556b-859a-49d939152f24',19,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','8a4727e6-fbe6-5432-b4a8-599602335537') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('930ca20a-3a8b-5e3f-808d-df34546ad162', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 6, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','930ca20a-3a8b-5e3f-808d-df34546ad162',20,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','8a4727e6-fbe6-5432-b4a8-599602335537') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('44fbd369-9065-5e22-a699-b24aa93b9601', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 5, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','44fbd369-9065-5e22-a699-b24aa93b9601',21,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','8a4727e6-fbe6-5432-b4a8-599602335537') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('8de1bc26-a647-58e4-8203-9bc6d8b3e304', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 6, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','8de1bc26-a647-58e4-8203-9bc6d8b3e304',22,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','8a4727e6-fbe6-5432-b4a8-599602335537') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('8b6bac38-71ca-531b-b9c8-84249df388b7', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 5, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','8b6bac38-71ca-531b-b9c8-84249df388b7',23,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','8a4727e6-fbe6-5432-b4a8-599602335537') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('987d53e8-d837-5805-b980-1a46735b26e0', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 6, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','987d53e8-d837-5805-b980-1a46735b26e0',24,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','8a4727e6-fbe6-5432-b4a8-599602335537') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('91421ee3-5405-5b8c-bee6-a242288fff74', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','91421ee3-5405-5b8c-bee6-a242288fff74',25,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','8a4727e6-fbe6-5432-b4a8-599602335537') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('02510cfc-7fe3-56d6-9d34-a1d5c30bf08b', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','02510cfc-7fe3-56d6-9d34-a1d5c30bf08b',26,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','8a4727e6-fbe6-5432-b4a8-599602335537') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('ebb38d23-59db-568e-b2c4-bef447a1a585', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','ebb38d23-59db-568e-b2c4-bef447a1a585',27,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','8a4727e6-fbe6-5432-b4a8-599602335537') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('58fadb9b-0f73-56d1-a522-6ee4b407e9bb', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 5, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','58fadb9b-0f73-56d1-a522-6ee4b407e9bb',28,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','421cace9-7377-5321-b974-fc7778de50a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('cef4d827-638c-50c8-9b27-0826cc9d8ee3', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 6, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','cef4d827-638c-50c8-9b27-0826cc9d8ee3',29,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','421cace9-7377-5321-b974-fc7778de50a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d6390abf-fbc0-5d04-b037-973df65b609e', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 5, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','d6390abf-fbc0-5d04-b037-973df65b609e',30,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','421cace9-7377-5321-b974-fc7778de50a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('968fa0b8-fdca-510a-9ebc-1e30189c417c', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 6, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','968fa0b8-fdca-510a-9ebc-1e30189c417c',31,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','421cace9-7377-5321-b974-fc7778de50a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('660ce46f-a466-5ca7-9795-8510b14e7b9a', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 5, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','660ce46f-a466-5ca7-9795-8510b14e7b9a',32,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','421cace9-7377-5321-b974-fc7778de50a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('a1d93d42-e50f-5222-af17-6df52157a097', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 6, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','a1d93d42-e50f-5222-af17-6df52157a097',33,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','421cace9-7377-5321-b974-fc7778de50a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('5cc1aab1-46e3-512b-a986-299833b6f623', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','5cc1aab1-46e3-512b-a986-299833b6f623',34,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','421cace9-7377-5321-b974-fc7778de50a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('4b504f2e-4342-599e-9c9e-def4c12c7965', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','4b504f2e-4342-599e-9c9e-def4c12c7965',35,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','421cace9-7377-5321-b974-fc7778de50a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('877b249c-fe50-590e-98e2-db639bc20c9c', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','877b249c-fe50-590e-98e2-db639bc20c9c',36,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','421cace9-7377-5321-b974-fc7778de50a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('07b9e9f9-22e6-56a5-b81b-077efdbb7d6c', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 6, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','07b9e9f9-22e6-56a5-b81b-077efdbb7d6c',37,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','6067749b-1a6c-55fd-bdc1-5770c9b50336') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('819065d4-c329-54da-bc82-51d32b480a8e', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 7, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','819065d4-c329-54da-bc82-51d32b480a8e',38,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','6067749b-1a6c-55fd-bdc1-5770c9b50336') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('2f11caae-6b9b-5d35-aff3-49b38a263fb1', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 6, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','2f11caae-6b9b-5d35-aff3-49b38a263fb1',39,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','6067749b-1a6c-55fd-bdc1-5770c9b50336') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('81f83658-ac29-54cb-b525-bc2cfa71382d', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 7, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','81f83658-ac29-54cb-b525-bc2cfa71382d',40,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','6067749b-1a6c-55fd-bdc1-5770c9b50336') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('67703571-094e-5ee2-a70c-d54815964efb', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 6, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','67703571-094e-5ee2-a70c-d54815964efb',41,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','6067749b-1a6c-55fd-bdc1-5770c9b50336') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('a663771e-d1f3-56b3-b29b-b796449dd797', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 7, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','a663771e-d1f3-56b3-b29b-b796449dd797',42,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','6067749b-1a6c-55fd-bdc1-5770c9b50336') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('919f9a71-741a-5cbe-9fd7-7d993beffc04', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','919f9a71-741a-5cbe-9fd7-7d993beffc04',43,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','6067749b-1a6c-55fd-bdc1-5770c9b50336') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('388bcf57-5b8f-5d0d-bf9b-ff67f646fa31', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','388bcf57-5b8f-5d0d-bf9b-ff67f646fa31',44,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','6067749b-1a6c-55fd-bdc1-5770c9b50336') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('7dd435d7-8437-5fc7-9dba-bad90ce90ee7', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','7dd435d7-8437-5fc7-9dba-bad90ce90ee7',45,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','6067749b-1a6c-55fd-bdc1-5770c9b50336') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('296daba3-e3d9-5cb0-9a97-525295d95ebf', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 6, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','296daba3-e3d9-5cb0-9a97-525295d95ebf',46,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d2466b20-d76d-5af2-a84d-61797bb807e1') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('75c4c580-afe5-5784-be03-68c1784adc18', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 7, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','75c4c580-afe5-5784-be03-68c1784adc18',47,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d2466b20-d76d-5af2-a84d-61797bb807e1') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('8f6194b2-c50c-5526-909e-c6819a9a928d', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 6, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','8f6194b2-c50c-5526-909e-c6819a9a928d',48,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d2466b20-d76d-5af2-a84d-61797bb807e1') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('aa44c83f-13db-5eee-bf17-a24aae20371c', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 7, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','aa44c83f-13db-5eee-bf17-a24aae20371c',49,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d2466b20-d76d-5af2-a84d-61797bb807e1') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('0ef48e6f-15c1-5298-8541-34845d819a5a', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 6, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','0ef48e6f-15c1-5298-8541-34845d819a5a',50,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d2466b20-d76d-5af2-a84d-61797bb807e1') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('21bf8911-602d-56fc-8886-e917c5669dfb', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 7, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','21bf8911-602d-56fc-8886-e917c5669dfb',51,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d2466b20-d76d-5af2-a84d-61797bb807e1') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('c1f71970-3e4a-5485-b3ff-f5778b7db476', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','c1f71970-3e4a-5485-b3ff-f5778b7db476',52,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d2466b20-d76d-5af2-a84d-61797bb807e1') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('72482264-1686-5077-81fa-eec79149eec6', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','72482264-1686-5077-81fa-eec79149eec6',53,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d2466b20-d76d-5af2-a84d-61797bb807e1') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('5ca82fae-66d1-59e9-9b50-9b7a68076b1a', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','5ca82fae-66d1-59e9-9b50-9b7a68076b1a',54,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','d2466b20-d76d-5af2-a84d-61797bb807e1') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('39f7979e-f279-575d-8a73-686eddd70a06', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 7, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','39f7979e-f279-575d-8a73-686eddd70a06',55,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','7a5ce1e2-e9d1-5766-90d6-f1bf75082918') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b7ed5190-b751-57a1-aacb-ea28a674a417', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 8, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','b7ed5190-b751-57a1-aacb-ea28a674a417',56,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','7a5ce1e2-e9d1-5766-90d6-f1bf75082918') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('3a2abec9-9014-5bcd-8a35-a4cd840c76d6', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 7, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','3a2abec9-9014-5bcd-8a35-a4cd840c76d6',57,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','7a5ce1e2-e9d1-5766-90d6-f1bf75082918') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('52e1bd71-8b2c-5509-bbb0-dc15bf5eff28', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 8, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','52e1bd71-8b2c-5509-bbb0-dc15bf5eff28',58,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','7a5ce1e2-e9d1-5766-90d6-f1bf75082918') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('de27939a-9968-5731-a796-0814e65cd51d', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 7, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','de27939a-9968-5731-a796-0814e65cd51d',59,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','7a5ce1e2-e9d1-5766-90d6-f1bf75082918') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('e41ee3ef-dcd3-5841-96ff-172a28d40764', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 8, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','e41ee3ef-dcd3-5841-96ff-172a28d40764',60,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','7a5ce1e2-e9d1-5766-90d6-f1bf75082918') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('7a5f512c-3cae-507d-92c3-d061cc66fedf', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','7a5f512c-3cae-507d-92c3-d061cc66fedf',61,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','7a5ce1e2-e9d1-5766-90d6-f1bf75082918') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('4de42f95-431a-5a82-a1b4-f547f1b40850', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 8, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','4de42f95-431a-5a82-a1b4-f547f1b40850',62,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','7a5ce1e2-e9d1-5766-90d6-f1bf75082918') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('bb57a2f9-d8eb-5378-975a-d305d0255a80', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','bb57a2f9-d8eb-5378-975a-d305d0255a80',63,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','7a5ce1e2-e9d1-5766-90d6-f1bf75082918') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('631261bc-7f82-5c27-bfde-ecf0d5a07939', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 7, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','631261bc-7f82-5c27-bfde-ecf0d5a07939',64,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','9eb0124e-c2f2-5f44-b423-bd8127515c1f') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('3d202e41-af4c-5767-aacd-dd25f7923ed4', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 8, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','3d202e41-af4c-5767-aacd-dd25f7923ed4',65,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','9eb0124e-c2f2-5f44-b423-bd8127515c1f') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('1dfccbee-8a1e-54e3-91a7-f8a43b34f821', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 7, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','1dfccbee-8a1e-54e3-91a7-f8a43b34f821',66,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','9eb0124e-c2f2-5f44-b423-bd8127515c1f') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('377cbc47-4920-5e28-ab5c-d2eb1b26b4f3', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 8, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','377cbc47-4920-5e28-ab5c-d2eb1b26b4f3',67,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','9eb0124e-c2f2-5f44-b423-bd8127515c1f') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('911ac1d0-5727-59c7-9a6b-c00ad851461c', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 7, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','911ac1d0-5727-59c7-9a6b-c00ad851461c',68,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','9eb0124e-c2f2-5f44-b423-bd8127515c1f') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9d250f8c-557a-5db3-ad37-c9a1b1400d9b', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 8, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','9d250f8c-557a-5db3-ad37-c9a1b1400d9b',69,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','9eb0124e-c2f2-5f44-b423-bd8127515c1f') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('e752c2cd-3bf1-5f3a-b132-79d78e123033', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','e752c2cd-3bf1-5f3a-b132-79d78e123033',70,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','9eb0124e-c2f2-5f44-b423-bd8127515c1f') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('4e8d2921-8866-5c27-ae34-0739da2bbd94', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 8, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','4e8d2921-8866-5c27-ae34-0739da2bbd94',71,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','9eb0124e-c2f2-5f44-b423-bd8127515c1f') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b8264825-5e02-588f-bfe1-81e445846645', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('5948272f-52c8-54ec-8112-66e9734c5bcf','b8264825-5e02-588f-bfe1-81e445846645',72,'a471dfe4-961a-5c7f-a4de-7337e4b5b620','9eb0124e-c2f2-5f44-b423-bd8127515c1f') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('e0af9fcb-ba98-534c-8701-8ad023cc4d0f','5948272f-52c8-54ec-8112-66e9734c5bcf','d83bd2b6-2ae6-5e20-a516-ba26397bd1a5','6067749b-1a6c-55fd-bdc1-5770c9b50336','SCORE_BELOW','{"threshold":0.35}'::jsonb,30);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('2c760db5-9b9d-53d8-be4f-63161e48f3f5','5948272f-52c8-54ec-8112-66e9734c5bcf','d83bd2b6-2ae6-5e20-a516-ba26397bd1a5','d2466b20-d76d-5af2-a84d-61797bb807e1','SCORE_ABOVE','{"threshold":0.65}'::jsonb,20);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('09db45c9-81a7-5c63-94f3-31d1abe70c13','5948272f-52c8-54ec-8112-66e9734c5bcf','d83bd2b6-2ae6-5e20-a516-ba26397bd1a5','c53294a1-a810-56c6-852e-67480eeeb2e4','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('d374f2f5-01bc-59ff-af84-9f95ddb685d4','5948272f-52c8-54ec-8112-66e9734c5bcf','c53294a1-a810-56c6-852e-67480eeeb2e4','7a5ce1e2-e9d1-5766-90d6-f1bf75082918','SCORE_ABOVE','{"threshold":0.7}'::jsonb,10);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('96641b3e-253b-5b36-92d1-7cbbd4e29c6c','5948272f-52c8-54ec-8112-66e9734c5bcf','c53294a1-a810-56c6-852e-67480eeeb2e4','421cace9-7377-5321-b974-fc7778de50a2','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('4dd2e31f-21fb-5d9c-a3b5-7ae3a59c1392','5948272f-52c8-54ec-8112-66e9734c5bcf','d2466b20-d76d-5af2-a84d-61797bb807e1','9eb0124e-c2f2-5f44-b423-bd8127515c1f','SCORE_ABOVE','{"threshold":0.7}'::jsonb,10);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('f6a4ddcb-417b-5ec6-b45d-c8aef2302a1c','5948272f-52c8-54ec-8112-66e9734c5bcf','d2466b20-d76d-5af2-a84d-61797bb807e1','421cace9-7377-5321-b974-fc7778de50a2','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('6eae2f3a-4e55-56c5-b173-ebe285b4e641','5948272f-52c8-54ec-8112-66e9734c5bcf','6067749b-1a6c-55fd-bdc1-5770c9b50336','8a4727e6-fbe6-5432-b4a8-599602335537','ALWAYS',NULL,0);
COMMIT;
