BEGIN;
INSERT INTO exams (id,title,description,year_level,domain,time_limit_seconds,available_from,available_until,status,created_by,package_type,scoring_config) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','Year 9 Grammar & Punctuation — Premium Practice Exam 09','Original NAPLAN-style Year 9 Grammar & Punctuation digital practice exam.',9,'GRAMMAR_PUNCTUATION',2700,NULL,NULL,'PUBLISHED',NULL,'PREMIUM',NULL);
INSERT INTO exam_sections (id,exam_id,title,section_order,time_limit_seconds,calculator_allowed,navigation_locked,domain,instructions) VALUES ('be231292-f54e-5efb-8d26-664c51907e11','6ab997f5-ef21-5a32-b60e-e95ab9f49a35','Grammar & Punctuation adaptive digital section',1,2700,FALSE,FALSE,'GRAMMAR_PUNCTUATION','Complete the adaptive practice section; the next testlet is selected by the configured routing rules.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('c6dd8db5-9377-57d5-afd7-b8fee47c15d6','be231292-f54e-5efb-8d26-664c51907e11',NULL,'A — Grammar & Punctuation adaptive node',1,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('be0f35aa-8e5e-5fd8-abe6-1da337a62a57','be231292-f54e-5efb-8d26-664c51907e11',NULL,'B — Grammar & Punctuation adaptive node',2,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('ca8ef02f-5a65-5b91-b0bc-6ebcf2313b73','be231292-f54e-5efb-8d26-664c51907e11',NULL,'B_LATE — Grammar & Punctuation adaptive node',3,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('3fa7547b-fefa-5dde-82c1-29b31e372d32','be231292-f54e-5efb-8d26-664c51907e11',NULL,'C — Grammar & Punctuation adaptive node',4,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('6f746b11-04a3-54ef-a721-6f6d210e8401','be231292-f54e-5efb-8d26-664c51907e11',NULL,'C_EARLY — Grammar & Punctuation adaptive node',5,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('a7286358-0924-5a46-82c7-402b419a7d47','be231292-f54e-5efb-8d26-664c51907e11',NULL,'D — Grammar & Punctuation adaptive node',6,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('d4f4e717-6f98-5fd9-9dc8-df77993cd5a2','be231292-f54e-5efb-8d26-664c51907e11',NULL,'E — Grammar & Punctuation adaptive node',7,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('856e3ba3-9923-591b-818e-87bd979d1c3b','be231292-f54e-5efb-8d26-664c51907e11',NULL,'F — Grammar & Punctuation adaptive node',8,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d3fab3cf-8389-5e7f-be7e-853b2f50d1b2', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 4, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','d3fab3cf-8389-5e7f-be7e-853b2f50d1b2',1,'be231292-f54e-5efb-8d26-664c51907e11','c6dd8db5-9377-57d5-afd7-b8fee47c15d6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('1e0faf80-2b61-5d0f-820a-6ca393807bb3', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 5, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','1e0faf80-2b61-5d0f-820a-6ca393807bb3',2,'be231292-f54e-5efb-8d26-664c51907e11','c6dd8db5-9377-57d5-afd7-b8fee47c15d6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b01f0bff-da14-5327-846f-690e58d8105f', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 4, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','b01f0bff-da14-5327-846f-690e58d8105f',3,'be231292-f54e-5efb-8d26-664c51907e11','c6dd8db5-9377-57d5-afd7-b8fee47c15d6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('057614bb-4d28-54fb-9e30-f2e5f3cfceb7', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 5, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','057614bb-4d28-54fb-9e30-f2e5f3cfceb7',4,'be231292-f54e-5efb-8d26-664c51907e11','c6dd8db5-9377-57d5-afd7-b8fee47c15d6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('f493d957-1076-5635-8baa-77783ae32b08', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 4, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','f493d957-1076-5635-8baa-77783ae32b08',5,'be231292-f54e-5efb-8d26-664c51907e11','c6dd8db5-9377-57d5-afd7-b8fee47c15d6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('100d4ec0-7515-5566-8b90-a691cb780b29', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 5, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','100d4ec0-7515-5566-8b90-a691cb780b29',6,'be231292-f54e-5efb-8d26-664c51907e11','c6dd8db5-9377-57d5-afd7-b8fee47c15d6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('776bf910-ccb9-5cc0-b1d4-d5db8c9c6333', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','776bf910-ccb9-5cc0-b1d4-d5db8c9c6333',7,'be231292-f54e-5efb-8d26-664c51907e11','c6dd8db5-9377-57d5-afd7-b8fee47c15d6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('5987739f-4dac-5ad1-9835-b4d34323034a', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','5987739f-4dac-5ad1-9835-b4d34323034a',8,'be231292-f54e-5efb-8d26-664c51907e11','c6dd8db5-9377-57d5-afd7-b8fee47c15d6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('7d6cdcf9-50d1-54ae-939e-2eda270ba357', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','7d6cdcf9-50d1-54ae-939e-2eda270ba357',9,'be231292-f54e-5efb-8d26-664c51907e11','c6dd8db5-9377-57d5-afd7-b8fee47c15d6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('8c44b06e-4fb4-5905-9e82-0ae9fd2c59fc', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 4, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','8c44b06e-4fb4-5905-9e82-0ae9fd2c59fc',10,'be231292-f54e-5efb-8d26-664c51907e11','be0f35aa-8e5e-5fd8-abe6-1da337a62a57') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('2fc60d79-2097-5ee1-bd94-29ee434f97eb', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 5, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','2fc60d79-2097-5ee1-bd94-29ee434f97eb',11,'be231292-f54e-5efb-8d26-664c51907e11','be0f35aa-8e5e-5fd8-abe6-1da337a62a57') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('4a411735-dec0-5eb3-b48c-c6d9eec1665c', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 4, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','4a411735-dec0-5eb3-b48c-c6d9eec1665c',12,'be231292-f54e-5efb-8d26-664c51907e11','be0f35aa-8e5e-5fd8-abe6-1da337a62a57') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('676074df-8007-54ef-a96d-fe0345f542ba', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 5, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','676074df-8007-54ef-a96d-fe0345f542ba',13,'be231292-f54e-5efb-8d26-664c51907e11','be0f35aa-8e5e-5fd8-abe6-1da337a62a57') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('43c4ea39-bd82-556a-b24c-5d569e7c22a6', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 4, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','43c4ea39-bd82-556a-b24c-5d569e7c22a6',14,'be231292-f54e-5efb-8d26-664c51907e11','be0f35aa-8e5e-5fd8-abe6-1da337a62a57') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('a6ec377a-9e18-5a32-9bbf-242b8cf3710b', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 5, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','a6ec377a-9e18-5a32-9bbf-242b8cf3710b',15,'be231292-f54e-5efb-8d26-664c51907e11','be0f35aa-8e5e-5fd8-abe6-1da337a62a57') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b29611d3-330f-5122-8e38-89caea000903', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','b29611d3-330f-5122-8e38-89caea000903',16,'be231292-f54e-5efb-8d26-664c51907e11','be0f35aa-8e5e-5fd8-abe6-1da337a62a57') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('ca3172f5-aad5-5765-a72d-62bcd44a8879', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','ca3172f5-aad5-5765-a72d-62bcd44a8879',17,'be231292-f54e-5efb-8d26-664c51907e11','be0f35aa-8e5e-5fd8-abe6-1da337a62a57') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('70ff79c8-6170-5022-a067-27666db32b52', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','70ff79c8-6170-5022-a067-27666db32b52',18,'be231292-f54e-5efb-8d26-664c51907e11','be0f35aa-8e5e-5fd8-abe6-1da337a62a57') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('28d9aa37-ba57-522a-9c64-94ea13de4f0d', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 5, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','28d9aa37-ba57-522a-9c64-94ea13de4f0d',19,'be231292-f54e-5efb-8d26-664c51907e11','ca8ef02f-5a65-5b91-b0bc-6ebcf2313b73') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('00e246d3-9f36-59e1-bf8b-4bc138037e7a', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 6, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','00e246d3-9f36-59e1-bf8b-4bc138037e7a',20,'be231292-f54e-5efb-8d26-664c51907e11','ca8ef02f-5a65-5b91-b0bc-6ebcf2313b73') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('6af32e89-6895-5e06-872f-33261648f31d', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 5, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','6af32e89-6895-5e06-872f-33261648f31d',21,'be231292-f54e-5efb-8d26-664c51907e11','ca8ef02f-5a65-5b91-b0bc-6ebcf2313b73') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('afc2240f-687c-5aea-87fb-c45e62ba7ad1', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 6, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','afc2240f-687c-5aea-87fb-c45e62ba7ad1',22,'be231292-f54e-5efb-8d26-664c51907e11','ca8ef02f-5a65-5b91-b0bc-6ebcf2313b73') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9db2f56f-7303-5750-9a6f-1491a888d42f', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 5, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','9db2f56f-7303-5750-9a6f-1491a888d42f',23,'be231292-f54e-5efb-8d26-664c51907e11','ca8ef02f-5a65-5b91-b0bc-6ebcf2313b73') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('f096bd02-bbf1-5581-abd5-eb7a22d3bde4', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 6, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','f096bd02-bbf1-5581-abd5-eb7a22d3bde4',24,'be231292-f54e-5efb-8d26-664c51907e11','ca8ef02f-5a65-5b91-b0bc-6ebcf2313b73') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('8df0a9b7-74ad-56d5-ae2f-b6db621319c1', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','8df0a9b7-74ad-56d5-ae2f-b6db621319c1',25,'be231292-f54e-5efb-8d26-664c51907e11','ca8ef02f-5a65-5b91-b0bc-6ebcf2313b73') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('cb585e98-e5be-5398-9795-5571448df947', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','cb585e98-e5be-5398-9795-5571448df947',26,'be231292-f54e-5efb-8d26-664c51907e11','ca8ef02f-5a65-5b91-b0bc-6ebcf2313b73') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('acd69101-42f9-585a-98d1-ef8530d07c42', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','acd69101-42f9-585a-98d1-ef8530d07c42',27,'be231292-f54e-5efb-8d26-664c51907e11','ca8ef02f-5a65-5b91-b0bc-6ebcf2313b73') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('243ecf01-b73a-55fe-8f1a-6af6e7c5844f', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 5, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','243ecf01-b73a-55fe-8f1a-6af6e7c5844f',28,'be231292-f54e-5efb-8d26-664c51907e11','3fa7547b-fefa-5dde-82c1-29b31e372d32') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('f7f4d00f-cdcf-5a6a-aa7b-ac49990f6f0a', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 6, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','f7f4d00f-cdcf-5a6a-aa7b-ac49990f6f0a',29,'be231292-f54e-5efb-8d26-664c51907e11','3fa7547b-fefa-5dde-82c1-29b31e372d32') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('8706893b-09e9-51b4-b986-03f74642c7ed', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 5, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','8706893b-09e9-51b4-b986-03f74642c7ed',30,'be231292-f54e-5efb-8d26-664c51907e11','3fa7547b-fefa-5dde-82c1-29b31e372d32') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('ba679756-5e63-5597-9718-6298fd4c578c', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 6, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','ba679756-5e63-5597-9718-6298fd4c578c',31,'be231292-f54e-5efb-8d26-664c51907e11','3fa7547b-fefa-5dde-82c1-29b31e372d32') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d0689e07-5d33-5b37-ac6a-04d8e8c790d7', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 5, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','d0689e07-5d33-5b37-ac6a-04d8e8c790d7',32,'be231292-f54e-5efb-8d26-664c51907e11','3fa7547b-fefa-5dde-82c1-29b31e372d32') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('be8c9704-6814-5598-b93b-24f52f254783', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 6, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','be8c9704-6814-5598-b93b-24f52f254783',33,'be231292-f54e-5efb-8d26-664c51907e11','3fa7547b-fefa-5dde-82c1-29b31e372d32') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('5e2b0fe0-134d-5f34-bd06-f15abe1b6db6', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','5e2b0fe0-134d-5f34-bd06-f15abe1b6db6',34,'be231292-f54e-5efb-8d26-664c51907e11','3fa7547b-fefa-5dde-82c1-29b31e372d32') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d90600e3-6463-5027-a255-b827b6d24791', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','d90600e3-6463-5027-a255-b827b6d24791',35,'be231292-f54e-5efb-8d26-664c51907e11','3fa7547b-fefa-5dde-82c1-29b31e372d32') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('7b0922fc-5eb6-5b82-8a45-0fb44af33af7', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','7b0922fc-5eb6-5b82-8a45-0fb44af33af7',36,'be231292-f54e-5efb-8d26-664c51907e11','3fa7547b-fefa-5dde-82c1-29b31e372d32') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d9e77ed7-7255-57b4-8840-4abc278c7528', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 6, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','d9e77ed7-7255-57b4-8840-4abc278c7528',37,'be231292-f54e-5efb-8d26-664c51907e11','6f746b11-04a3-54ef-a721-6f6d210e8401') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('65ea3933-9e90-5dc8-a940-6ec97393f31b', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 7, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','65ea3933-9e90-5dc8-a940-6ec97393f31b',38,'be231292-f54e-5efb-8d26-664c51907e11','6f746b11-04a3-54ef-a721-6f6d210e8401') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('5ac18e09-ed51-5ad1-9df1-1b005c3dd987', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 6, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','5ac18e09-ed51-5ad1-9df1-1b005c3dd987',39,'be231292-f54e-5efb-8d26-664c51907e11','6f746b11-04a3-54ef-a721-6f6d210e8401') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d60456b9-7319-5b5b-a45c-53093705891c', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 7, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','d60456b9-7319-5b5b-a45c-53093705891c',40,'be231292-f54e-5efb-8d26-664c51907e11','6f746b11-04a3-54ef-a721-6f6d210e8401') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('bca4d299-530a-5e7e-b1f1-7a00326a6f99', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 6, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','bca4d299-530a-5e7e-b1f1-7a00326a6f99',41,'be231292-f54e-5efb-8d26-664c51907e11','6f746b11-04a3-54ef-a721-6f6d210e8401') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('0bf103bb-8c54-5b35-9fc3-8f8b5de86642', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 7, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','0bf103bb-8c54-5b35-9fc3-8f8b5de86642',42,'be231292-f54e-5efb-8d26-664c51907e11','6f746b11-04a3-54ef-a721-6f6d210e8401') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('33872cee-6081-5e7c-b1db-0cc54f0d164a', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','33872cee-6081-5e7c-b1db-0cc54f0d164a',43,'be231292-f54e-5efb-8d26-664c51907e11','6f746b11-04a3-54ef-a721-6f6d210e8401') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('ea8a0e54-61fc-5188-9023-a6f474c71254', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','ea8a0e54-61fc-5188-9023-a6f474c71254',44,'be231292-f54e-5efb-8d26-664c51907e11','6f746b11-04a3-54ef-a721-6f6d210e8401') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('8faebbb2-e916-56f0-aabb-80106efa0eb9', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','8faebbb2-e916-56f0-aabb-80106efa0eb9',45,'be231292-f54e-5efb-8d26-664c51907e11','6f746b11-04a3-54ef-a721-6f6d210e8401') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('adeb289b-4d89-554d-9ede-ae88eccf4c27', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 6, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','adeb289b-4d89-554d-9ede-ae88eccf4c27',46,'be231292-f54e-5efb-8d26-664c51907e11','a7286358-0924-5a46-82c7-402b419a7d47') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('79f8e7b6-2f35-5e9d-b79e-0726905f9c03', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 7, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','79f8e7b6-2f35-5e9d-b79e-0726905f9c03',47,'be231292-f54e-5efb-8d26-664c51907e11','a7286358-0924-5a46-82c7-402b419a7d47') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('bc168b33-f298-5cbd-a5ab-aaca2aa60ff8', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 6, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','bc168b33-f298-5cbd-a5ab-aaca2aa60ff8',48,'be231292-f54e-5efb-8d26-664c51907e11','a7286358-0924-5a46-82c7-402b419a7d47') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('0a63a1dd-b803-5b9e-a8e3-3d897afbb711', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 7, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','0a63a1dd-b803-5b9e-a8e3-3d897afbb711',49,'be231292-f54e-5efb-8d26-664c51907e11','a7286358-0924-5a46-82c7-402b419a7d47') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9daa6439-1cdd-5102-9eb6-c7751552f069', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 6, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','9daa6439-1cdd-5102-9eb6-c7751552f069',50,'be231292-f54e-5efb-8d26-664c51907e11','a7286358-0924-5a46-82c7-402b419a7d47') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d86508b0-86da-5159-9f59-fccf4d1d1712', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 7, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','d86508b0-86da-5159-9f59-fccf4d1d1712',51,'be231292-f54e-5efb-8d26-664c51907e11','a7286358-0924-5a46-82c7-402b419a7d47') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('cb06c9a7-8512-542c-b78f-891e2da3ae12', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','cb06c9a7-8512-542c-b78f-891e2da3ae12',52,'be231292-f54e-5efb-8d26-664c51907e11','a7286358-0924-5a46-82c7-402b419a7d47') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('711c427e-24dc-56a2-9fb2-dc235cb31d49', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','711c427e-24dc-56a2-9fb2-dc235cb31d49',53,'be231292-f54e-5efb-8d26-664c51907e11','a7286358-0924-5a46-82c7-402b419a7d47') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('ff374f9c-907d-5787-8b72-08c86739b920', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','ff374f9c-907d-5787-8b72-08c86739b920',54,'be231292-f54e-5efb-8d26-664c51907e11','a7286358-0924-5a46-82c7-402b419a7d47') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('ad3839fa-5732-5166-a505-b723a788ca12', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 7, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','ad3839fa-5732-5166-a505-b723a788ca12',55,'be231292-f54e-5efb-8d26-664c51907e11','d4f4e717-6f98-5fd9-9dc8-df77993cd5a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('146383a9-de2b-5de5-a88c-9187b98f533e', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 8, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','146383a9-de2b-5de5-a88c-9187b98f533e',56,'be231292-f54e-5efb-8d26-664c51907e11','d4f4e717-6f98-5fd9-9dc8-df77993cd5a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('4b17a841-29c4-5ded-8fd8-c4bb5555683b', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 7, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','4b17a841-29c4-5ded-8fd8-c4bb5555683b',57,'be231292-f54e-5efb-8d26-664c51907e11','d4f4e717-6f98-5fd9-9dc8-df77993cd5a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('92c4fb2b-eea5-5c1d-a629-5e61bd20070a', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 8, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','92c4fb2b-eea5-5c1d-a629-5e61bd20070a',58,'be231292-f54e-5efb-8d26-664c51907e11','d4f4e717-6f98-5fd9-9dc8-df77993cd5a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9e1e35a3-01e4-508c-a8ce-0901fde7dd89', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 7, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','9e1e35a3-01e4-508c-a8ce-0901fde7dd89',59,'be231292-f54e-5efb-8d26-664c51907e11','d4f4e717-6f98-5fd9-9dc8-df77993cd5a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('dc4ead10-938d-504c-b46e-ad6f18170d0a', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 8, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','dc4ead10-938d-504c-b46e-ad6f18170d0a',60,'be231292-f54e-5efb-8d26-664c51907e11','d4f4e717-6f98-5fd9-9dc8-df77993cd5a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9c174255-7480-5286-85cc-b82974c546f4', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','9c174255-7480-5286-85cc-b82974c546f4',61,'be231292-f54e-5efb-8d26-664c51907e11','d4f4e717-6f98-5fd9-9dc8-df77993cd5a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('e14dfc55-8984-5dec-bd53-dd5c1bfa2652', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 8, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','e14dfc55-8984-5dec-bd53-dd5c1bfa2652',62,'be231292-f54e-5efb-8d26-664c51907e11','d4f4e717-6f98-5fd9-9dc8-df77993cd5a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('bb6dcc90-9fad-5b88-8349-48f83f87717e', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','bb6dcc90-9fad-5b88-8349-48f83f87717e',63,'be231292-f54e-5efb-8d26-664c51907e11','d4f4e717-6f98-5fd9-9dc8-df77993cd5a2') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('a8c2caa6-7a1d-5982-913b-dc431d38a330', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 7, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','a8c2caa6-7a1d-5982-913b-dc431d38a330',64,'be231292-f54e-5efb-8d26-664c51907e11','856e3ba3-9923-591b-818e-87bd979d1c3b') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('a66a25ec-9e7f-5fa5-965d-99c1e98a1608', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 8, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','a66a25ec-9e7f-5fa5-965d-99c1e98a1608',65,'be231292-f54e-5efb-8d26-664c51907e11','856e3ba3-9923-591b-818e-87bd979d1c3b') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('53ad0efc-dce5-5d17-97c8-2464d7a3978e', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 7, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','53ad0efc-dce5-5d17-97c8-2464d7a3978e',66,'be231292-f54e-5efb-8d26-664c51907e11','856e3ba3-9923-591b-818e-87bd979d1c3b') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('274c2440-672d-5cba-8851-1eefe36232f6', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 8, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','274c2440-672d-5cba-8851-1eefe36232f6',67,'be231292-f54e-5efb-8d26-664c51907e11','856e3ba3-9923-591b-818e-87bd979d1c3b') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9f9b04ee-3335-51a2-b7a9-07798b0f25f6', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 7, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','9f9b04ee-3335-51a2-b7a9-07798b0f25f6',68,'be231292-f54e-5efb-8d26-664c51907e11','856e3ba3-9923-591b-818e-87bd979d1c3b') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('001810ea-30ab-5881-816e-351b8f4e51db', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 8, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','001810ea-30ab-5881-816e-351b8f4e51db',69,'be231292-f54e-5efb-8d26-664c51907e11','856e3ba3-9923-591b-818e-87bd979d1c3b') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('557f2ae3-9432-5d93-848a-6b1a9fd1db75', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','557f2ae3-9432-5d93-848a-6b1a9fd1db75',70,'be231292-f54e-5efb-8d26-664c51907e11','856e3ba3-9923-591b-818e-87bd979d1c3b') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b64c8c2d-a49e-5c7a-ad38-c119a1b4e588', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 8, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','b64c8c2d-a49e-5c7a-ad38-c119a1b4e588',71,'be231292-f54e-5efb-8d26-664c51907e11','856e3ba3-9923-591b-818e-87bd979d1c3b') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b00765a2-80b0-536f-a397-efcfba7e5e10', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('6ab997f5-ef21-5a32-b60e-e95ab9f49a35','b00765a2-80b0-536f-a397-efcfba7e5e10',72,'be231292-f54e-5efb-8d26-664c51907e11','856e3ba3-9923-591b-818e-87bd979d1c3b') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('a49b7a80-2f3e-5568-ae6c-a03d43441c9d','6ab997f5-ef21-5a32-b60e-e95ab9f49a35','c6dd8db5-9377-57d5-afd7-b8fee47c15d6','6f746b11-04a3-54ef-a721-6f6d210e8401','SCORE_BELOW','{"threshold":0.35}'::jsonb,30);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('18d1d023-cc8a-5410-b786-8b81a8106393','6ab997f5-ef21-5a32-b60e-e95ab9f49a35','c6dd8db5-9377-57d5-afd7-b8fee47c15d6','a7286358-0924-5a46-82c7-402b419a7d47','SCORE_ABOVE','{"threshold":0.65}'::jsonb,20);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('1c9072d1-3476-591f-8ff4-2866fb215987','6ab997f5-ef21-5a32-b60e-e95ab9f49a35','c6dd8db5-9377-57d5-afd7-b8fee47c15d6','be0f35aa-8e5e-5fd8-abe6-1da337a62a57','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('833bca3e-8789-58a1-8e71-84769ab76178','6ab997f5-ef21-5a32-b60e-e95ab9f49a35','be0f35aa-8e5e-5fd8-abe6-1da337a62a57','d4f4e717-6f98-5fd9-9dc8-df77993cd5a2','SCORE_ABOVE','{"threshold":0.7}'::jsonb,10);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('3161b51c-e5a5-5745-aa91-a13db2549e11','6ab997f5-ef21-5a32-b60e-e95ab9f49a35','be0f35aa-8e5e-5fd8-abe6-1da337a62a57','3fa7547b-fefa-5dde-82c1-29b31e372d32','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('2df3a8ac-92d5-58e3-b3ed-8790aa11b60d','6ab997f5-ef21-5a32-b60e-e95ab9f49a35','a7286358-0924-5a46-82c7-402b419a7d47','856e3ba3-9923-591b-818e-87bd979d1c3b','SCORE_ABOVE','{"threshold":0.7}'::jsonb,10);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('cee7623a-808c-51a5-919e-10e5b3c0af99','6ab997f5-ef21-5a32-b60e-e95ab9f49a35','a7286358-0924-5a46-82c7-402b419a7d47','3fa7547b-fefa-5dde-82c1-29b31e372d32','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('6e7e7702-2ba6-5528-8727-57e9c94d338b','6ab997f5-ef21-5a32-b60e-e95ab9f49a35','6f746b11-04a3-54ef-a721-6f6d210e8401','ca8ef02f-5a65-5b91-b0bc-6ebcf2313b73','ALWAYS',NULL,0);
COMMIT;
