BEGIN;
INSERT INTO exams (id,title,description,year_level,domain,time_limit_seconds,available_from,available_until,status,created_by,package_type,scoring_config) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','Year 7 Grammar & Punctuation — Advanced Practice Exam 02','Original NAPLAN-style Year 7 Grammar & Punctuation digital practice exam.',7,'GRAMMAR_PUNCTUATION',2700,NULL,NULL,'PUBLISHED',NULL,'ADVANCED',NULL);
INSERT INTO exam_sections (id,exam_id,title,section_order,time_limit_seconds,calculator_allowed,navigation_locked,domain,instructions) VALUES ('4ff08a8b-2aeb-581e-b02a-64981814cb6a','cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','Grammar & Punctuation adaptive digital section',1,2700,FALSE,FALSE,'GRAMMAR_PUNCTUATION','Complete the adaptive practice section; the next testlet is selected by the configured routing rules.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('1118af30-fee7-5785-8622-4e06ee317ee4','4ff08a8b-2aeb-581e-b02a-64981814cb6a',NULL,'A — Grammar & Punctuation adaptive node',1,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('fdf43252-af96-5b4a-bcbc-244a2bc92333','4ff08a8b-2aeb-581e-b02a-64981814cb6a',NULL,'B — Grammar & Punctuation adaptive node',2,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('d0d97940-145e-5594-85bf-90126097c187','4ff08a8b-2aeb-581e-b02a-64981814cb6a',NULL,'B_LATE — Grammar & Punctuation adaptive node',3,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('e74fba72-db7a-5b95-a768-5b96b93eacbe','4ff08a8b-2aeb-581e-b02a-64981814cb6a',NULL,'C — Grammar & Punctuation adaptive node',4,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('eb24ddc7-a131-51d4-a585-4c0264670680','4ff08a8b-2aeb-581e-b02a-64981814cb6a',NULL,'C_EARLY — Grammar & Punctuation adaptive node',5,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('3596f32b-d9b2-5a81-a8df-00dfcf84fa8c','4ff08a8b-2aeb-581e-b02a-64981814cb6a',NULL,'D — Grammar & Punctuation adaptive node',6,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('ab40136b-4b6f-5ed5-986e-74a994a2a888','4ff08a8b-2aeb-581e-b02a-64981814cb6a',NULL,'E — Grammar & Punctuation adaptive node',7,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('c9dd190e-4af6-592c-a95e-adadfb88a9f6','4ff08a8b-2aeb-581e-b02a-64981814cb6a',NULL,'F — Grammar & Punctuation adaptive node',8,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9debf03d-2e3d-541f-9104-0453c9ec3c15', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 4, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','9debf03d-2e3d-541f-9104-0453c9ec3c15',1,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','1118af30-fee7-5785-8622-4e06ee317ee4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('1721fd80-3f11-5681-8fa8-9c0622b11798', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 5, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','1721fd80-3f11-5681-8fa8-9c0622b11798',2,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','1118af30-fee7-5785-8622-4e06ee317ee4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('1602ad7e-b09d-5dce-8a5f-ad8e6a0aea33', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 4, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','1602ad7e-b09d-5dce-8a5f-ad8e6a0aea33',3,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','1118af30-fee7-5785-8622-4e06ee317ee4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('05a6af24-72d7-537d-bc8c-8e41c565198a', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 5, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','05a6af24-72d7-537d-bc8c-8e41c565198a',4,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','1118af30-fee7-5785-8622-4e06ee317ee4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('de122151-ef70-51ee-ba3c-ca154778053e', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 4, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','de122151-ef70-51ee-ba3c-ca154778053e',5,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','1118af30-fee7-5785-8622-4e06ee317ee4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('930bff9d-6ab3-5cb3-8ab0-f7845eb0d31b', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 5, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','930bff9d-6ab3-5cb3-8ab0-f7845eb0d31b',6,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','1118af30-fee7-5785-8622-4e06ee317ee4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('4a7e9aa4-f452-522b-9bfe-d66e9918bc96', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, ‘I will finish the poster tomorrow.’"},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','4a7e9aa4-f452-522b-9bfe-d66e9918bc96',7,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','1118af30-fee7-5785-8622-4e06ee317ee4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('4d8fab48-29e4-588b-b86c-2b5b652c8b7c', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','4d8fab48-29e4-588b-b86c-2b5b652c8b7c',8,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','1118af30-fee7-5785-8622-4e06ee317ee4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('37783d75-c437-586d-9164-a162a5286730', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','37783d75-c437-586d-9164-a162a5286730',9,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','1118af30-fee7-5785-8622-4e06ee317ee4') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('e14c68dd-73f2-5094-af3d-d09176c89ebb', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 4, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','e14c68dd-73f2-5094-af3d-d09176c89ebb',10,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','fdf43252-af96-5b4a-bcbc-244a2bc92333') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('dd2299a4-c80b-59bd-8ad8-5de309219045', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 5, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','dd2299a4-c80b-59bd-8ad8-5de309219045',11,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','fdf43252-af96-5b4a-bcbc-244a2bc92333') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('53b31e39-d58b-51ac-8c10-5994d59cfa68', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 4, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','53b31e39-d58b-51ac-8c10-5994d59cfa68',12,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','fdf43252-af96-5b4a-bcbc-244a2bc92333') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('511ed407-011b-5b9d-b56f-d4acd127c863', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 5, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','511ed407-011b-5b9d-b56f-d4acd127c863',13,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','fdf43252-af96-5b4a-bcbc-244a2bc92333') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('5777cba4-dc94-5ccd-819d-fa78ec89480a', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 4, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','5777cba4-dc94-5ccd-819d-fa78ec89480a',14,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','fdf43252-af96-5b4a-bcbc-244a2bc92333') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('44e9ef0f-9ffa-5305-bfc9-c356eb8185b1', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 5, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','44e9ef0f-9ffa-5305-bfc9-c356eb8185b1',15,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','fdf43252-af96-5b4a-bcbc-244a2bc92333') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('bd670b92-4b5e-5b85-b248-c1786b126749', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','bd670b92-4b5e-5b85-b248-c1786b126749',16,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','fdf43252-af96-5b4a-bcbc-244a2bc92333') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('6fbcbc61-0aca-5e9d-ae6b-490a6305d8f8', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','6fbcbc61-0aca-5e9d-ae6b-490a6305d8f8',17,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','fdf43252-af96-5b4a-bcbc-244a2bc92333') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d2223086-9e52-5ea6-b965-ae4375f076ee', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things, whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','d2223086-9e52-5ea6-b965-ae4375f076ee',18,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','fdf43252-af96-5b4a-bcbc-244a2bc92333') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('86ff634a-4fe7-5a50-b89b-716c9d41483f', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 5, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','86ff634a-4fe7-5a50-b89b-716c9d41483f',19,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','d0d97940-145e-5594-85bf-90126097c187') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('136d8c69-5664-5964-88e0-0eb7d980ad69', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 6, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','136d8c69-5664-5964-88e0-0eb7d980ad69',20,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','d0d97940-145e-5594-85bf-90126097c187') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9b5756f0-084d-5d8a-8185-cada641aec21', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 5, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','9b5756f0-084d-5d8a-8185-cada641aec21',21,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','d0d97940-145e-5594-85bf-90126097c187') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('60a19ee0-d329-5d5d-88ee-0706381ff1d2', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 6, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','60a19ee0-d329-5d5d-88ee-0706381ff1d2',22,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','d0d97940-145e-5594-85bf-90126097c187') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('732e1156-c921-5d25-82ee-ecf227d61e5d', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 5, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','732e1156-c921-5d25-82ee-ecf227d61e5d',23,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','d0d97940-145e-5594-85bf-90126097c187') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('c1d1c12d-6bbe-5034-a4a1-e324d2ec9977', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 6, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','c1d1c12d-6bbe-5034-a4a1-e324d2ec9977',24,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','d0d97940-145e-5594-85bf-90126097c187') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('074249f2-a2ad-5b60-8dde-36342d51902e', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','074249f2-a2ad-5b60-8dde-36342d51902e',25,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','d0d97940-145e-5594-85bf-90126097c187') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('a4727cd1-284b-50d2-83da-40151bc31c6e', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things, whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','a4727cd1-284b-50d2-83da-40151bc31c6e',26,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','d0d97940-145e-5594-85bf-90126097c187') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('5f5d15fa-156b-5c1f-b0d8-38789d2bbec4', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, ‘I will finish the poster tomorrow.’"},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','5f5d15fa-156b-5c1f-b0d8-38789d2bbec4',27,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','d0d97940-145e-5594-85bf-90126097c187') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9e9dbda0-56b2-5682-aac5-313a48728c19', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 5, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','9e9dbda0-56b2-5682-aac5-313a48728c19',28,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','e74fba72-db7a-5b95-a768-5b96b93eacbe') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('157851f0-9452-50cb-b662-0efa84ff5219', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 6, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','157851f0-9452-50cb-b662-0efa84ff5219',29,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','e74fba72-db7a-5b95-a768-5b96b93eacbe') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('0527cabd-8e27-5493-9015-9f9978d1d415', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 5, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','0527cabd-8e27-5493-9015-9f9978d1d415',30,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','e74fba72-db7a-5b95-a768-5b96b93eacbe') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('fe2479e1-7499-5eb6-89bf-4e02338ae0e7', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 6, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','fe2479e1-7499-5eb6-89bf-4e02338ae0e7',31,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','e74fba72-db7a-5b95-a768-5b96b93eacbe') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('e9a45b9d-8196-5176-99a2-62a98e5c0e6f', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 5, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','e9a45b9d-8196-5176-99a2-62a98e5c0e6f',32,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','e74fba72-db7a-5b95-a768-5b96b93eacbe') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('05c51caa-b1a8-5528-bfe3-b4b8a1e57608', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 6, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','05c51caa-b1a8-5528-bfe3-b4b8a1e57608',33,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','e74fba72-db7a-5b95-a768-5b96b93eacbe') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('3a30164c-a492-573b-ab39-886aa275c7f2', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things, whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','3a30164c-a492-573b-ab39-886aa275c7f2',34,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','e74fba72-db7a-5b95-a768-5b96b93eacbe') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('8051653b-8cf7-5487-bf8c-0d703d51af9c', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, ‘I will finish the poster tomorrow.’"},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','8051653b-8cf7-5487-bf8c-0d703d51af9c',35,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','e74fba72-db7a-5b95-a768-5b96b93eacbe') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9ef0e3d0-006b-5698-b5aa-d2aa7e534250', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','9ef0e3d0-006b-5698-b5aa-d2aa7e534250',36,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','e74fba72-db7a-5b95-a768-5b96b93eacbe') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('520b9ea1-f3d1-5b59-a3dc-b3664604eccd', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 6, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','520b9ea1-f3d1-5b59-a3dc-b3664604eccd',37,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','eb24ddc7-a131-51d4-a585-4c0264670680') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('8f865844-cdce-55c6-9e35-64ee114dc660', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 7, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','8f865844-cdce-55c6-9e35-64ee114dc660',38,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','eb24ddc7-a131-51d4-a585-4c0264670680') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('3a0da435-964b-5ab3-a81d-6d81ccc43985', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 6, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','3a0da435-964b-5ab3-a81d-6d81ccc43985',39,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','eb24ddc7-a131-51d4-a585-4c0264670680') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('f54cdc5c-6aca-5ebe-a817-648705babcea', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 7, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','f54cdc5c-6aca-5ebe-a817-648705babcea',40,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','eb24ddc7-a131-51d4-a585-4c0264670680') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('f78d5761-4431-51e3-84a5-af24368e402c', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 6, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','f78d5761-4431-51e3-84a5-af24368e402c',41,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','eb24ddc7-a131-51d4-a585-4c0264670680') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('3701eef7-3fd8-57ed-b39d-dee9ba987c8c', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 7, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','3701eef7-3fd8-57ed-b39d-dee9ba987c8c',42,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','eb24ddc7-a131-51d4-a585-4c0264670680') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('98b66d86-bd94-5955-b127-fa9c53be80f5', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, ‘I will finish the poster tomorrow.’"},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','98b66d86-bd94-5955-b127-fa9c53be80f5',43,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','eb24ddc7-a131-51d4-a585-4c0264670680') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('cab71b05-96a0-514e-bce1-90e3f189fd5f', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','cab71b05-96a0-514e-bce1-90e3f189fd5f',44,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','eb24ddc7-a131-51d4-a585-4c0264670680') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('75b268f1-3f9e-5059-952c-1918d05ba250', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','75b268f1-3f9e-5059-952c-1918d05ba250',45,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','eb24ddc7-a131-51d4-a585-4c0264670680') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('0b2bbc54-540a-5b20-81f2-d00ce32e295f', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 6, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','0b2bbc54-540a-5b20-81f2-d00ce32e295f',46,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','3596f32b-d9b2-5a81-a8df-00dfcf84fa8c') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('ce5d0812-be35-5d8b-9e6e-9efe4911f1a4', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 7, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','ce5d0812-be35-5d8b-9e6e-9efe4911f1a4',47,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','3596f32b-d9b2-5a81-a8df-00dfcf84fa8c') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('0f7b0293-b1bb-5edf-84ce-b3e914f5dee5', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 6, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','0f7b0293-b1bb-5edf-84ce-b3e914f5dee5',48,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','3596f32b-d9b2-5a81-a8df-00dfcf84fa8c') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('5386e743-338a-59a5-a06e-1bb33a04e4c8', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 7, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','5386e743-338a-59a5-a06e-1bb33a04e4c8',49,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','3596f32b-d9b2-5a81-a8df-00dfcf84fa8c') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('947562ca-3f6a-58c2-8533-a7bf6e1f40fe', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 6, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','947562ca-3f6a-58c2-8533-a7bf6e1f40fe',50,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','3596f32b-d9b2-5a81-a8df-00dfcf84fa8c') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9986d491-add3-5a1a-b888-2e48db706fbd', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 7, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','9986d491-add3-5a1a-b888-2e48db706fbd',51,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','3596f32b-d9b2-5a81-a8df-00dfcf84fa8c') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('5b61ab71-ef1c-54ab-b578-56034b734021', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','5b61ab71-ef1c-54ab-b578-56034b734021',52,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','3596f32b-d9b2-5a81-a8df-00dfcf84fa8c') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('7fba0296-91ff-543e-8504-7978068cf2d0', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','7fba0296-91ff-543e-8504-7978068cf2d0',53,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','3596f32b-d9b2-5a81-a8df-00dfcf84fa8c') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('5eca0319-691c-51d2-9d16-d0fb28518a65', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things, whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','5eca0319-691c-51d2-9d16-d0fb28518a65',54,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','3596f32b-d9b2-5a81-a8df-00dfcf84fa8c') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d799192d-d305-5870-b02d-d997e0488322', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 7, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','d799192d-d305-5870-b02d-d997e0488322',55,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','ab40136b-4b6f-5ed5-986e-74a994a2a888') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b9ed96e3-9ace-5660-a4b2-869ee3f3950b', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 8, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','b9ed96e3-9ace-5660-a4b2-869ee3f3950b',56,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','ab40136b-4b6f-5ed5-986e-74a994a2a888') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('3897e386-e3f4-5349-b383-d3e6528d393d', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 7, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','3897e386-e3f4-5349-b383-d3e6528d393d',57,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','ab40136b-4b6f-5ed5-986e-74a994a2a888') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('ce225254-9913-5cc1-a88f-dbd4b5673f80', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 8, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','ce225254-9913-5cc1-a88f-dbd4b5673f80',58,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','ab40136b-4b6f-5ed5-986e-74a994a2a888') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('40b476b7-9171-509f-89b1-9ef13ada8f7c', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 7, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','40b476b7-9171-509f-89b1-9ef13ada8f7c',59,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','ab40136b-4b6f-5ed5-986e-74a994a2a888') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('1041fe9e-b82e-50ff-99c4-68710cb69b45', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 8, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','1041fe9e-b82e-50ff-99c4-68710cb69b45',60,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','ab40136b-4b6f-5ed5-986e-74a994a2a888') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('05f8d2f3-db4c-538f-bed9-02c3096f43ce', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','05f8d2f3-db4c-538f-bed9-02c3096f43ce',61,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','ab40136b-4b6f-5ed5-986e-74a994a2a888') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('a7fd8d6a-1b72-5cb7-8e3b-bfd5091e79dc', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 8, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things, whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','a7fd8d6a-1b72-5cb7-8e3b-bfd5091e79dc',62,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','ab40136b-4b6f-5ed5-986e-74a994a2a888') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('a11ed2a7-1961-579e-81b6-43d931da54de', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, ‘I will finish the poster tomorrow.’"},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','a11ed2a7-1961-579e-81b6-43d931da54de',63,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','ab40136b-4b6f-5ed5-986e-74a994a2a888') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('3e2defa7-d435-5a7a-bf03-824b8ba4751b', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 7, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','3e2defa7-d435-5a7a-bf03-824b8ba4751b',64,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','c9dd190e-4af6-592c-a95e-adadfb88a9f6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('930ccc8a-401a-5004-b624-b5c4ded511a2', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 8, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','930ccc8a-401a-5004-b624-b5c4ded511a2',65,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','c9dd190e-4af6-592c-a95e-adadfb88a9f6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('a704e8e6-258c-55cc-9b75-4963bfa452ce', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 7, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','a704e8e6-258c-55cc-9b75-4963bfa452ce',66,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','c9dd190e-4af6-592c-a95e-adadfb88a9f6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('bb04c6c2-03f9-5edf-8b7f-626133af9cf1', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 8, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','bb04c6c2-03f9-5edf-8b7f-626133af9cf1',67,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','c9dd190e-4af6-592c-a95e-adadfb88a9f6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('74b60e10-5015-5604-b493-f4d445567857', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 7, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','74b60e10-5015-5604-b493-f4d445567857',68,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','c9dd190e-4af6-592c-a95e-adadfb88a9f6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('fe82221c-fd32-59af-907d-c02a8ef3b976', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Word choice', 8, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','fe82221c-fd32-59af-907d-c02a8ef3b976',69,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','c9dd190e-4af6-592c-a95e-adadfb88a9f6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('ce25d185-2218-5995-a589-455994a6f1ab', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things, whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','ce25d185-2218-5995-a589-455994a6f1ab',70,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','c9dd190e-4af6-592c-a95e-adadfb88a9f6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('146e3c8a-dcd5-58eb-92d1-0d56ac2fe086', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Commas', 8, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, ‘I will finish the poster tomorrow.’"},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','146e3c8a-dcd5-58eb-92d1-0d56ac2fe086',71,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','c9dd190e-4af6-592c-a95e-adadfb88a9f6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('0f43eca4-61bc-5c91-99a5-54befc0c6a96', 'MULTIPLE_CHOICE', 7, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'ADVANCED', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','0f43eca4-61bc-5c91-99a5-54befc0c6a96',72,'4ff08a8b-2aeb-581e-b02a-64981814cb6a','c9dd190e-4af6-592c-a95e-adadfb88a9f6') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('bf67a7ae-bc02-5863-94e4-77964adbccaf','cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','1118af30-fee7-5785-8622-4e06ee317ee4','eb24ddc7-a131-51d4-a585-4c0264670680','SCORE_BELOW','{"threshold":0.35}'::jsonb,30);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('86c2c74b-bfdb-59b9-b952-4e2e7954cdc0','cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','1118af30-fee7-5785-8622-4e06ee317ee4','3596f32b-d9b2-5a81-a8df-00dfcf84fa8c','SCORE_ABOVE','{"threshold":0.65}'::jsonb,20);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('8d4614b0-dfdc-54fc-81da-7b99c0b1bccc','cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','1118af30-fee7-5785-8622-4e06ee317ee4','fdf43252-af96-5b4a-bcbc-244a2bc92333','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('256b2d94-cf1a-545d-a1f3-36826733534e','cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','fdf43252-af96-5b4a-bcbc-244a2bc92333','ab40136b-4b6f-5ed5-986e-74a994a2a888','SCORE_ABOVE','{"threshold":0.7}'::jsonb,10);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('368a15a5-72f4-5b8e-9073-facaaa84de00','cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','fdf43252-af96-5b4a-bcbc-244a2bc92333','e74fba72-db7a-5b95-a768-5b96b93eacbe','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('013040c5-8469-503d-9b17-cd36895c3263','cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','3596f32b-d9b2-5a81-a8df-00dfcf84fa8c','c9dd190e-4af6-592c-a95e-adadfb88a9f6','SCORE_ABOVE','{"threshold":0.7}'::jsonb,10);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('a51537f2-0451-5ddc-9fb7-77ab191e0421','cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','3596f32b-d9b2-5a81-a8df-00dfcf84fa8c','e74fba72-db7a-5b95-a768-5b96b93eacbe','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('061ed4ef-0922-5ac0-afe0-613d843661d4','cf3ebfb7-cad0-5f3b-8485-f163a67e68d4','eb24ddc7-a131-51d4-a585-4c0264670680','d0d97940-145e-5594-85bf-90126097c187','ALWAYS',NULL,0);
COMMIT;
