BEGIN;
INSERT INTO exams (id,title,description,year_level,domain,time_limit_seconds,available_from,available_until,status,created_by,package_type,scoring_config) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','Year 9 Grammar & Punctuation — Premium Practice Exam 01','Original NAPLAN-style Year 9 Grammar & Punctuation digital practice exam.',9,'GRAMMAR_PUNCTUATION',2700,NULL,NULL,'PUBLISHED',NULL,'PREMIUM',NULL);
INSERT INTO exam_sections (id,exam_id,title,section_order,time_limit_seconds,calculator_allowed,navigation_locked,domain,instructions) VALUES ('f238e98c-c5de-5131-80d8-4656c74b6cae','991f64ff-e360-5de2-9ced-e7ade08a98a4','Grammar & Punctuation adaptive digital section',1,2700,FALSE,FALSE,'GRAMMAR_PUNCTUATION','Complete the adaptive practice section; the next testlet is selected by the configured routing rules.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('281ebed6-9e9e-557e-bf5d-ba366a6dbaa0','f238e98c-c5de-5131-80d8-4656c74b6cae',NULL,'A — Grammar & Punctuation adaptive node',1,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('88b55195-e28f-5a3e-85f3-3573bdf5c02a','f238e98c-c5de-5131-80d8-4656c74b6cae',NULL,'B — Grammar & Punctuation adaptive node',2,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('26882533-5a91-5183-971f-a842e1a131ed','f238e98c-c5de-5131-80d8-4656c74b6cae',NULL,'B_LATE — Grammar & Punctuation adaptive node',3,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('fa927045-0135-53f0-bc1a-272eb10a4259','f238e98c-c5de-5131-80d8-4656c74b6cae',NULL,'C — Grammar & Punctuation adaptive node',4,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('5087dcf7-c3fe-52c8-bfd3-d0d5ccd83462','f238e98c-c5de-5131-80d8-4656c74b6cae',NULL,'C_EARLY — Grammar & Punctuation adaptive node',5,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('ba135b9b-5fb0-51e0-99e1-431e32e868d3','f238e98c-c5de-5131-80d8-4656c74b6cae',NULL,'D — Grammar & Punctuation adaptive node',6,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('70dc16ca-98e7-5b57-88df-0195bd8697fb','f238e98c-c5de-5131-80d8-4656c74b6cae',NULL,'E — Grammar & Punctuation adaptive node',7,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO testlets (id,section_id,stimulus_id,title,testlet_order,is_branching_node,navigation_locked,calculator_allowed,instructions) VALUES ('ea97d75b-2776-5ba3-8b7a-528c9ffbb525','f238e98c-c5de-5131-80d8-4656c74b6cae',NULL,'F — Grammar & Punctuation adaptive node',8,TRUE,FALSE,FALSE,'Complete all questions in this testlet before continuing.');
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9e650fed-16cc-5b99-80d1-9c5b36ba94a5', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 4, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','9e650fed-16cc-5b99-80d1-9c5b36ba94a5',1,'f238e98c-c5de-5131-80d8-4656c74b6cae','281ebed6-9e9e-557e-bf5d-ba366a6dbaa0') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('817f5a67-eed7-59bd-b5c7-8c16ffda4184', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 5, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','817f5a67-eed7-59bd-b5c7-8c16ffda4184',2,'f238e98c-c5de-5131-80d8-4656c74b6cae','281ebed6-9e9e-557e-bf5d-ba366a6dbaa0') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('97096eef-09a9-5d35-a151-74b8d487c388', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 4, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','97096eef-09a9-5d35-a151-74b8d487c388',3,'f238e98c-c5de-5131-80d8-4656c74b6cae','281ebed6-9e9e-557e-bf5d-ba366a6dbaa0') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('e20c84a7-d7c3-53d1-8b13-bae23a4063b1', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 5, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','e20c84a7-d7c3-53d1-8b13-bae23a4063b1',4,'f238e98c-c5de-5131-80d8-4656c74b6cae','281ebed6-9e9e-557e-bf5d-ba366a6dbaa0') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('2dc55a6b-2291-558b-89c9-1544de92d7e9', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 4, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','2dc55a6b-2291-558b-89c9-1544de92d7e9',5,'f238e98c-c5de-5131-80d8-4656c74b6cae','281ebed6-9e9e-557e-bf5d-ba366a6dbaa0') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('7a9e9294-ef9c-59d9-ad29-592125d210cc', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 5, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','7a9e9294-ef9c-59d9-ad29-592125d210cc',6,'f238e98c-c5de-5131-80d8-4656c74b6cae','281ebed6-9e9e-557e-bf5d-ba366a6dbaa0') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('a7ea900f-c69c-5496-b6e1-657d3d28cd41', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','a7ea900f-c69c-5496-b6e1-657d3d28cd41',7,'f238e98c-c5de-5131-80d8-4656c74b6cae','281ebed6-9e9e-557e-bf5d-ba366a6dbaa0') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('0fca5b23-27a7-59c5-b7f7-14337bb2052c', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','0fca5b23-27a7-59c5-b7f7-14337bb2052c',8,'f238e98c-c5de-5131-80d8-4656c74b6cae','281ebed6-9e9e-557e-bf5d-ba366a6dbaa0') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('dfa3490e-5054-5815-8dc3-347e0d2346c8', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','dfa3490e-5054-5815-8dc3-347e0d2346c8',9,'f238e98c-c5de-5131-80d8-4656c74b6cae','281ebed6-9e9e-557e-bf5d-ba366a6dbaa0') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('4fb0edb1-24e3-5c89-bbda-b72dd7eb6c66', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 4, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','4fb0edb1-24e3-5c89-bbda-b72dd7eb6c66',10,'f238e98c-c5de-5131-80d8-4656c74b6cae','88b55195-e28f-5a3e-85f3-3573bdf5c02a') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('e60f7d34-45c5-5d7c-a07d-7849204f174b', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 5, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','e60f7d34-45c5-5d7c-a07d-7849204f174b',11,'f238e98c-c5de-5131-80d8-4656c74b6cae','88b55195-e28f-5a3e-85f3-3573bdf5c02a') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('63241795-dd9b-526a-a144-50b5a3b3066a', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 4, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','63241795-dd9b-526a-a144-50b5a3b3066a',12,'f238e98c-c5de-5131-80d8-4656c74b6cae','88b55195-e28f-5a3e-85f3-3573bdf5c02a') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('54f0f539-64ce-5a64-998a-db4d7eb56641', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 5, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','54f0f539-64ce-5a64-998a-db4d7eb56641',13,'f238e98c-c5de-5131-80d8-4656c74b6cae','88b55195-e28f-5a3e-85f3-3573bdf5c02a') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('e9c78c13-8021-5827-8907-aad9fe3e3876', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 4, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','e9c78c13-8021-5827-8907-aad9fe3e3876',14,'f238e98c-c5de-5131-80d8-4656c74b6cae','88b55195-e28f-5a3e-85f3-3573bdf5c02a') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('4531d66a-5eb6-5aa9-b934-d4d864a6e80d', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 5, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','4531d66a-5eb6-5aa9-b934-d4d864a6e80d',15,'f238e98c-c5de-5131-80d8-4656c74b6cae','88b55195-e28f-5a3e-85f3-3573bdf5c02a') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('193bc5af-0783-5047-9b1c-2d8d7edf245f', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','193bc5af-0783-5047-9b1c-2d8d7edf245f',16,'f238e98c-c5de-5131-80d8-4656c74b6cae','88b55195-e28f-5a3e-85f3-3573bdf5c02a') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('786a275f-14a7-5731-8eac-b8156516df32', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','786a275f-14a7-5731-8eac-b8156516df32',17,'f238e98c-c5de-5131-80d8-4656c74b6cae','88b55195-e28f-5a3e-85f3-3573bdf5c02a') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('3be2bc0e-d34a-54ac-bc02-fc0c408e8557', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 4, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','3be2bc0e-d34a-54ac-bc02-fc0c408e8557',18,'f238e98c-c5de-5131-80d8-4656c74b6cae','88b55195-e28f-5a3e-85f3-3573bdf5c02a') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('068e2ed7-772f-5297-9353-85a7ea0d1b73', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 5, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','068e2ed7-772f-5297-9353-85a7ea0d1b73',19,'f238e98c-c5de-5131-80d8-4656c74b6cae','26882533-5a91-5183-971f-a842e1a131ed') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('bb48504f-2d26-5c04-ad0a-24b1606b2bd2', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 6, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','bb48504f-2d26-5c04-ad0a-24b1606b2bd2',20,'f238e98c-c5de-5131-80d8-4656c74b6cae','26882533-5a91-5183-971f-a842e1a131ed') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b8fabd6c-b407-5e74-9c73-340a68841ca4', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 5, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','b8fabd6c-b407-5e74-9c73-340a68841ca4',21,'f238e98c-c5de-5131-80d8-4656c74b6cae','26882533-5a91-5183-971f-a842e1a131ed') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('05fff4b0-341e-5e1b-a279-83e1ab144d8e', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 6, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','05fff4b0-341e-5e1b-a279-83e1ab144d8e',22,'f238e98c-c5de-5131-80d8-4656c74b6cae','26882533-5a91-5183-971f-a842e1a131ed') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('af6ce6a0-90f1-54aa-b75a-9e4c964f9843', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 5, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','af6ce6a0-90f1-54aa-b75a-9e4c964f9843',23,'f238e98c-c5de-5131-80d8-4656c74b6cae','26882533-5a91-5183-971f-a842e1a131ed') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('ba777c31-65e8-5e07-8a89-b3d16939d0bd', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 6, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','ba777c31-65e8-5e07-8a89-b3d16939d0bd',24,'f238e98c-c5de-5131-80d8-4656c74b6cae','26882533-5a91-5183-971f-a842e1a131ed') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('0da6ee99-82ca-5f9d-a9ff-030c66ba4c17', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','0da6ee99-82ca-5f9d-a9ff-030c66ba4c17',25,'f238e98c-c5de-5131-80d8-4656c74b6cae','26882533-5a91-5183-971f-a842e1a131ed') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b6bfdb8a-ef2f-5e98-98d6-e715aaecf746', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','b6bfdb8a-ef2f-5e98-98d6-e715aaecf746',26,'f238e98c-c5de-5131-80d8-4656c74b6cae','26882533-5a91-5183-971f-a842e1a131ed') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('6492b8a4-70f2-5fd0-b9e6-e0fb1202405d', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','6492b8a4-70f2-5fd0-b9e6-e0fb1202405d',27,'f238e98c-c5de-5131-80d8-4656c74b6cae','26882533-5a91-5183-971f-a842e1a131ed') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('2309ef28-9625-5079-9f34-1dcb2d2d0bfe', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 5, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','2309ef28-9625-5079-9f34-1dcb2d2d0bfe',28,'f238e98c-c5de-5131-80d8-4656c74b6cae','fa927045-0135-53f0-bc1a-272eb10a4259') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('2a9b7e33-d493-546d-b490-bfdf252389b9', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 6, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','2a9b7e33-d493-546d-b490-bfdf252389b9',29,'f238e98c-c5de-5131-80d8-4656c74b6cae','fa927045-0135-53f0-bc1a-272eb10a4259') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('e18b5861-08d0-5ddc-ae11-b4408296af1f', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 5, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','e18b5861-08d0-5ddc-ae11-b4408296af1f',30,'f238e98c-c5de-5131-80d8-4656c74b6cae','fa927045-0135-53f0-bc1a-272eb10a4259') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('f14cb4ea-65e0-52b0-9404-3a4d6e3dc2df', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 6, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','f14cb4ea-65e0-52b0-9404-3a4d6e3dc2df',31,'f238e98c-c5de-5131-80d8-4656c74b6cae','fa927045-0135-53f0-bc1a-272eb10a4259') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('86c81351-6b4a-500f-a2a7-92b61cf38258', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 5, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','86c81351-6b4a-500f-a2a7-92b61cf38258',32,'f238e98c-c5de-5131-80d8-4656c74b6cae','fa927045-0135-53f0-bc1a-272eb10a4259') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('9d6e38ce-8f36-594e-9ae3-f54f4a6a26e8', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 6, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','9d6e38ce-8f36-594e-9ae3-f54f4a6a26e8',33,'f238e98c-c5de-5131-80d8-4656c74b6cae','fa927045-0135-53f0-bc1a-272eb10a4259') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('c3a91868-94c4-5abc-83bc-21db478ecb64', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','c3a91868-94c4-5abc-83bc-21db478ecb64',34,'f238e98c-c5de-5131-80d8-4656c74b6cae','fa927045-0135-53f0-bc1a-272eb10a4259') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('83d742ce-a2e3-584c-b009-0317ea2a5f1c', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','83d742ce-a2e3-584c-b009-0317ea2a5f1c',35,'f238e98c-c5de-5131-80d8-4656c74b6cae','fa927045-0135-53f0-bc1a-272eb10a4259') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('fbfd5e10-5726-5b89-a37d-041a8c0b82ed', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 5, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'EASY', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','fbfd5e10-5726-5b89-a37d-041a8c0b82ed',36,'f238e98c-c5de-5131-80d8-4656c74b6cae','fa927045-0135-53f0-bc1a-272eb10a4259') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('526415b6-c49a-5d14-85bb-0a879c61bf32', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 6, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','526415b6-c49a-5d14-85bb-0a879c61bf32',37,'f238e98c-c5de-5131-80d8-4656c74b6cae','5087dcf7-c3fe-52c8-bfd3-d0d5ccd83462') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('299f5524-b7dd-556a-ae0e-167b1a409074', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 7, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','299f5524-b7dd-556a-ae0e-167b1a409074',38,'f238e98c-c5de-5131-80d8-4656c74b6cae','5087dcf7-c3fe-52c8-bfd3-d0d5ccd83462') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('fc1302ab-3162-51e3-a2c9-9e463d28dfb0', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 6, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','fc1302ab-3162-51e3-a2c9-9e463d28dfb0',39,'f238e98c-c5de-5131-80d8-4656c74b6cae','5087dcf7-c3fe-52c8-bfd3-d0d5ccd83462') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('95311e05-193a-5a60-996a-adfa3e4a9866', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 7, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','95311e05-193a-5a60-996a-adfa3e4a9866',40,'f238e98c-c5de-5131-80d8-4656c74b6cae','5087dcf7-c3fe-52c8-bfd3-d0d5ccd83462') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('54d9d501-a8b3-55dd-8073-09e3b581e02c', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 6, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','54d9d501-a8b3-55dd-8073-09e3b581e02c',41,'f238e98c-c5de-5131-80d8-4656c74b6cae','5087dcf7-c3fe-52c8-bfd3-d0d5ccd83462') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('ed227a01-83d4-598b-855e-90cd1dc8b528', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 7, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','ed227a01-83d4-598b-855e-90cd1dc8b528',42,'f238e98c-c5de-5131-80d8-4656c74b6cae','5087dcf7-c3fe-52c8-bfd3-d0d5ccd83462') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('3feb61a7-8eb4-5f33-ae5e-aa99f992548b', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','3feb61a7-8eb4-5f33-ae5e-aa99f992548b',43,'f238e98c-c5de-5131-80d8-4656c74b6cae','5087dcf7-c3fe-52c8-bfd3-d0d5ccd83462') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('2d86a0c2-e250-576f-878a-07cf5f11a4b6', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','2d86a0c2-e250-576f-878a-07cf5f11a4b6',44,'f238e98c-c5de-5131-80d8-4656c74b6cae','5087dcf7-c3fe-52c8-bfd3-d0d5ccd83462') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('0ae2b042-6976-57d0-b4ca-1c75bf94fa4b', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','0ae2b042-6976-57d0-b4ca-1c75bf94fa4b',45,'f238e98c-c5de-5131-80d8-4656c74b6cae','5087dcf7-c3fe-52c8-bfd3-d0d5ccd83462') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('8d07a379-b89d-5a9d-bfeb-e79ec36de9f3', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 6, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','8d07a379-b89d-5a9d-bfeb-e79ec36de9f3',46,'f238e98c-c5de-5131-80d8-4656c74b6cae','ba135b9b-5fb0-51e0-99e1-431e32e868d3') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('66d13855-e358-5592-888d-f5202e43240b', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 7, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','66d13855-e358-5592-888d-f5202e43240b',47,'f238e98c-c5de-5131-80d8-4656c74b6cae','ba135b9b-5fb0-51e0-99e1-431e32e868d3') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('4e8a89c9-2d78-5bb0-bc2f-a12613de44ca', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 6, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','4e8a89c9-2d78-5bb0-bc2f-a12613de44ca',48,'f238e98c-c5de-5131-80d8-4656c74b6cae','ba135b9b-5fb0-51e0-99e1-431e32e868d3') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('30ff2601-567c-5ca9-b646-6f3de7dfb994', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 7, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','30ff2601-567c-5ca9-b646-6f3de7dfb994',49,'f238e98c-c5de-5131-80d8-4656c74b6cae','ba135b9b-5fb0-51e0-99e1-431e32e868d3') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('6e0a9dee-f878-5842-8c3f-14fd51bbca60', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 6, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','6e0a9dee-f878-5842-8c3f-14fd51bbca60',50,'f238e98c-c5de-5131-80d8-4656c74b6cae','ba135b9b-5fb0-51e0-99e1-431e32e868d3') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('26cc53bd-3260-52c7-9bf6-998b3a432131', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 7, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','26cc53bd-3260-52c7-9bf6-998b3a432131',51,'f238e98c-c5de-5131-80d8-4656c74b6cae','ba135b9b-5fb0-51e0-99e1-431e32e868d3') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('94b45a47-1dbe-52ca-aa5e-8b728536688c', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','94b45a47-1dbe-52ca-aa5e-8b728536688c',52,'f238e98c-c5de-5131-80d8-4656c74b6cae','ba135b9b-5fb0-51e0-99e1-431e32e868d3') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('fb3564b2-0035-52f8-b143-dbb73e8a9325', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','fb3564b2-0035-52f8-b143-dbb73e8a9325',53,'f238e98c-c5de-5131-80d8-4656c74b6cae','ba135b9b-5fb0-51e0-99e1-431e32e868d3') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('0aa9b471-82c2-5fbc-bb1f-6fb16338cdd6', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 6, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'MEDIUM', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','0aa9b471-82c2-5fbc-bb1f-6fb16338cdd6',54,'f238e98c-c5de-5131-80d8-4656c74b6cae','ba135b9b-5fb0-51e0-99e1-431e32e868d3') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('167bef2d-06d1-533e-8d91-e1872b4b7704', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 7, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','167bef2d-06d1-533e-8d91-e1872b4b7704',55,'f238e98c-c5de-5131-80d8-4656c74b6cae','70dc16ca-98e7-5b57-88df-0195bd8697fb') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('5226550a-51ca-5fe2-a41e-0d179070be74', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 8, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','5226550a-51ca-5fe2-a41e-0d179070be74',56,'f238e98c-c5de-5131-80d8-4656c74b6cae','70dc16ca-98e7-5b57-88df-0195bd8697fb') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('6beccf5b-dfd3-53ba-87ff-93b2cabe6fb2', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 7, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','6beccf5b-dfd3-53ba-87ff-93b2cabe6fb2',57,'f238e98c-c5de-5131-80d8-4656c74b6cae','70dc16ca-98e7-5b57-88df-0195bd8697fb') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('4a40eadc-e0b3-550d-a912-cbf7f9af8367', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 8, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','4a40eadc-e0b3-550d-a912-cbf7f9af8367',58,'f238e98c-c5de-5131-80d8-4656c74b6cae','70dc16ca-98e7-5b57-88df-0195bd8697fb') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('f9755738-e02e-573f-a841-774ff5bab906', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 7, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','f9755738-e02e-573f-a841-774ff5bab906',59,'f238e98c-c5de-5131-80d8-4656c74b6cae','70dc16ca-98e7-5b57-88df-0195bd8697fb') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('5b9b23d3-8bd9-53bf-8ad0-aa06d5238514', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 8, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','5b9b23d3-8bd9-53bf-8ad0-aa06d5238514',60,'f238e98c-c5de-5131-80d8-4656c74b6cae','70dc16ca-98e7-5b57-88df-0195bd8697fb') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d796d3ab-a296-5cd6-820e-d2e2804f3039', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"After the race the organisers packed the cones."},{"label":"B","text":"After the race; the organisers packed the cones."},{"label":"C","text":"After the race, the organisers, packed the cones."},{"label":"D","text":"After the race, the organisers packed the cones."}]'::jsonb, '{"value":"D"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','d796d3ab-a296-5cd6-820e-d2e2804f3039',61,'f238e98c-c5de-5131-80d8-4656c74b6cae','70dc16ca-98e7-5b57-88df-0195bd8697fb') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('b9e01f89-3670-5b7a-b1e9-c76e34cf6d5d', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 8, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','b9e01f89-3670-5b7a-b1e9-c76e34cf6d5d',62,'f238e98c-c5de-5131-80d8-4656c74b6cae','70dc16ca-98e7-5b57-88df-0195bd8697fb') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('f8215f17-20a0-5aba-9a8d-dc705fc98e72', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','f8215f17-20a0-5aba-9a8d-dc705fc98e72',63,'f238e98c-c5de-5131-80d8-4656c74b6cae','70dc16ca-98e7-5b57-88df-0195bd8697fb') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('33d7fb87-92b5-54da-9a0e-92f5c4474414', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Subject-verb agreement', 7, NULL, NULL, 'Which word correctly completes the sentence?

Neither of the volunteers ___ forgotten the key.', '[{"label":"A","text":"were"},{"label":"B","text":"has"},{"label":"C","text":"are"},{"label":"D","text":"have"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form has correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','33d7fb87-92b5-54da-9a0e-92f5c4474414',64,'f238e98c-c5de-5131-80d8-4656c74b6cae','ea97d75b-2776-5ba3-8b7a-528c9ffbb525') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('48559270-696d-58d9-bd37-1e5ca75bbbe5', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Pronoun reference', 8, NULL, NULL, 'Which word correctly completes the sentence?

By the time the bus arrived, the students ___ their bags.', '[{"label":"A","text":"pack"},{"label":"B","text":"had packed"},{"label":"C","text":"are packing"},{"label":"D","text":"have packed"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form had packed correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','48559270-696d-58d9-bd37-1e5ca75bbbe5',65,'f238e98c-c5de-5131-80d8-4656c74b6cae','ea97d75b-2776-5ba3-8b7a-528c9ffbb525') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('8b486bb7-a96d-5c0c-b0a1-9385b13672e2', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Tense and consistency', 7, NULL, NULL, 'Which word correctly completes the sentence?

The coach asked Sam and ___ to check the equipment.', '[{"label":"A","text":"mine"},{"label":"B","text":"me"},{"label":"C","text":"my"},{"label":"D","text":"I"}]'::jsonb, '{"value":"B"}'::jsonb, 'The form me correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','8b486bb7-a96d-5c0c-b0a1-9385b13672e2',66,'f238e98c-c5de-5131-80d8-4656c74b6cae','ea97d75b-2776-5ba3-8b7a-528c9ffbb525') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('7f258add-23af-5250-9dc0-a8bc82a4bd39', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Clause boundaries', 8, NULL, NULL, 'Which word correctly completes the sentence?

The organisers said they ___ extend the session if the weather stayed fine.', '[{"label":"A","text":"can"},{"label":"B","text":"will"},{"label":"C","text":"must"},{"label":"D","text":"could"}]'::jsonb, '{"value":"D"}'::jsonb, 'The form could correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','7f258add-23af-5250-9dc0-a8bc82a4bd39',67,'f238e98c-c5de-5131-80d8-4656c74b6cae','ea97d75b-2776-5ba3-8b7a-528c9ffbb525') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('e22dc46a-575d-5228-85ae-4f13702b996c', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Modal verbs', 7, NULL, NULL, 'Which word correctly completes the sentence?

The reason the team left early ___ that the lights had failed.', '[{"label":"A","text":"have"},{"label":"B","text":"are"},{"label":"C","text":"was"},{"label":"D","text":"were"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form was correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','e22dc46a-575d-5228-85ae-4f13702b996c',68,'f238e98c-c5de-5131-80d8-4656c74b6cae','ea97d75b-2776-5ba3-8b7a-528c9ffbb525') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('39184bf5-8d1f-551c-95df-da8c83ee02a5', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Word choice', 8, NULL, NULL, 'Which word correctly completes the sentence?

The list of tasks ___ on the noticeboard each Monday.', '[{"label":"A","text":"have appeared"},{"label":"B","text":"appearing"},{"label":"C","text":"appears"},{"label":"D","text":"appear"}]'::jsonb, '{"value":"C"}'::jsonb, 'The form appears correctly fits the grammatical structure.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','39184bf5-8d1f-551c-95df-da8c83ee02a5',69,'f238e98c-c5de-5131-80d8-4656c74b6cae','ea97d75b-2776-5ba3-8b7a-528c9ffbb525') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('2e92ebc5-273b-5497-b763-13099a0483aa', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Apostrophes', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The team brought three things: whistles, water and maps."},{"label":"B","text":"The team brought three things: whistles water and maps."},{"label":"C","text":"The team brought three things; whistles, water and maps."},{"label":"D","text":"The team brought three things whistles water and maps."}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','2e92ebc5-273b-5497-b763-13099a0483aa',70,'f238e98c-c5de-5131-80d8-4656c74b6cae','ea97d75b-2776-5ba3-8b7a-528c9ffbb525') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('d8cd0ffd-c145-537f-a3a8-973320056c70', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Commas', 8, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"Mia said, “I will finish the poster tomorrow.”"},{"label":"B","text":"Mia said I will finish the poster tomorrow."},{"label":"C","text":"Mia said, “I will finish the poster tomorrow”."},{"label":"D","text":"Mia said “I will finish the poster tomorrow.”"}]'::jsonb, '{"value":"A"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','d8cd0ffd-c145-537f-a3a8-973320056c70',71,'f238e98c-c5de-5131-80d8-4656c74b6cae','ea97d75b-2776-5ba3-8b7a-528c9ffbb525') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO questions (id, question_type, year_level, domain, topic, difficulty_band, stimulus_text, stimulus_type, question_text, options, correct_answer, explanation, status, created_by, package_type, difficulty, marks, cognitive_skill, curriculum_strand, audio_url, stimulus_id, calculator_allowed, marking_rubric) VALUES ('1121b97f-b294-5972-b093-479a72ac7705', 'MULTIPLE_CHOICE', 9, 'GRAMMAR_PUNCTUATION', 'Quotation marks', 7, NULL, NULL, 'Which sentence is punctuated correctly?', '[{"label":"A","text":"The weather changed suddenly , however, the event continued."},{"label":"B","text":"The weather changed suddenly; however, the event continued."},{"label":"C","text":"The weather changed suddenly; however the event continued."},{"label":"D","text":"The weather changed suddenly however the event continued."}]'::jsonb, '{"value":"B"}'::jsonb, 'The correct sentence uses the required punctuation.', 'PUBLISHED', NULL, 'PREMIUM', 'HARD', 1, 'APPLICATION', 'Language conventions', NULL, NULL, TRUE, NULL) ;
INSERT INTO exam_questions (exam_id,question_id,question_order,section_id,testlet_id) VALUES ('991f64ff-e360-5de2-9ced-e7ade08a98a4','1121b97f-b294-5972-b093-479a72ac7705',72,'f238e98c-c5de-5131-80d8-4656c74b6cae','ea97d75b-2776-5ba3-8b7a-528c9ffbb525') ON CONFLICT (exam_id,question_id) DO NOTHING;
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('d6cc4ba6-9a4a-5663-bd77-b5bacf6cd7fe','991f64ff-e360-5de2-9ced-e7ade08a98a4','281ebed6-9e9e-557e-bf5d-ba366a6dbaa0','5087dcf7-c3fe-52c8-bfd3-d0d5ccd83462','SCORE_BELOW','{"threshold":0.35}'::jsonb,30);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('de55e070-dca8-55f2-936d-dae5cadd7271','991f64ff-e360-5de2-9ced-e7ade08a98a4','281ebed6-9e9e-557e-bf5d-ba366a6dbaa0','ba135b9b-5fb0-51e0-99e1-431e32e868d3','SCORE_ABOVE','{"threshold":0.65}'::jsonb,20);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('af88ec01-6335-505d-a316-1164289caa77','991f64ff-e360-5de2-9ced-e7ade08a98a4','281ebed6-9e9e-557e-bf5d-ba366a6dbaa0','88b55195-e28f-5a3e-85f3-3573bdf5c02a','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('62dcc57a-eeb2-5166-9543-e28434d3bb6e','991f64ff-e360-5de2-9ced-e7ade08a98a4','88b55195-e28f-5a3e-85f3-3573bdf5c02a','70dc16ca-98e7-5b57-88df-0195bd8697fb','SCORE_ABOVE','{"threshold":0.7}'::jsonb,10);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('3da5a900-e375-5d79-a999-974c148bb46c','991f64ff-e360-5de2-9ced-e7ade08a98a4','88b55195-e28f-5a3e-85f3-3573bdf5c02a','fa927045-0135-53f0-bc1a-272eb10a4259','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('228022e6-46d8-5332-b101-8e10ea0566fd','991f64ff-e360-5de2-9ced-e7ade08a98a4','ba135b9b-5fb0-51e0-99e1-431e32e868d3','ea97d75b-2776-5ba3-8b7a-528c9ffbb525','SCORE_ABOVE','{"threshold":0.7}'::jsonb,10);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('915d83db-f1af-587f-8f16-7f82b1e98713','991f64ff-e360-5de2-9ced-e7ade08a98a4','ba135b9b-5fb0-51e0-99e1-431e32e868d3','fa927045-0135-53f0-bc1a-272eb10a4259','ALWAYS',NULL,0);
INSERT INTO testlet_transitions (id,exam_id,source_testlet,target_testlet,condition_type,condition_value,priority) VALUES ('6d61c9e7-a01a-567b-be96-f2a9d0939afd','991f64ff-e360-5de2-9ced-e7ade08a98a4','5087dcf7-c3fe-52c8-bfd3-d0d5ccd83462','26882533-5a91-5183-971f-a842e1a131ed','ALWAYS',NULL,0);
COMMIT;
